import React, { useEffect, useState } from 'react';
import { AlertTriangle, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog';

const statusLabels = { active: 'Ativo', replaced: 'Substituído', revoked: 'Revogado' };
const formatDate = (value) => value ? new Intl.DateTimeFormat('pt-BR', { timeZone: 'UTC' }).format(new Date(value)) : 'sem término';
const emptyGuardianForm = () => ({ name: '', relationship: '', valid_from: '', valid_until: '', consent_recorded: false, replacement_reason: '' });

export default function LegalGuardianCard({ patientId, episodeId, isMinor = false, guardians = [], onSave, onRevoke }) {
  const [adding, setAdding] = useState(false); const [busy, setBusy] = useState(false);
  const [form, setForm] = useState(emptyGuardianForm);
  const [revoking, setRevoking] = useState(null); const [reason, setReason] = useState(''); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  const active = guardians.find((guardian) => guardian.status === 'active');
  const resetForm = () => { setForm(emptyGuardianForm()); setError(''); };
  useEffect(() => { if (!adding) { setForm(emptyGuardianForm()); setError(''); } }, [adding]);
  const save = async (event) => { event.preventDefault(); setError(''); if (active && !form.replacement_reason.trim()) { setError('Motivo da substituição é obrigatório.'); return; } const payload = { name: form.name, relationship: form.relationship, valid_from: form.valid_from || null, valid_until: form.valid_until || null, consent: { recorded: form.consent_recorded }, ...(active ? { reason: form.replacement_reason.trim() } : {}) }; setBusy(true); const result = await onSave?.(patientId, episodeId, payload); setBusy(false); if (result?.error) setError('Não foi possível salvar o responsável.'); else { setAdding(false); resetForm(); setSuccess(active ? 'Responsável substituído com sucesso.' : 'Responsável salvo com sucesso.'); } };
  const revoke = async () => { if (!reason.trim()) { setError('Informe o motivo da revogação.'); return; } setBusy(true); const result = await onRevoke?.(revoking.id, reason.trim()); setBusy(false); if (result?.error) setError('Não foi possível revogar o responsável.'); else { setRevoking(null); setReason(''); setSuccess('Responsável revogado com sucesso.'); } };
  return <Card><CardHeader><CardTitle>Responsável legal</CardTitle><p className="text-sm text-muted-foreground">Vínculo válido somente para o episódio de cuidado atual.</p></CardHeader><CardContent className="space-y-4">
    {!episodeId && <p role="status" className="rounded-md border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900">Inicie um episódio de cuidado para registrar um responsável legal.</p>}
    {isMinor && !active && <p role="alert" className="flex gap-2 rounded-md border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900"><AlertTriangle className="h-4 w-4 shrink-0" />Menor sem responsável legal ativo.</p>}
    {guardians.length === 0 && <p className="text-sm text-muted-foreground">Nenhum responsável legal registrado neste episódio.</p>}
    {guardians.map((g) => <div key={g.id} className="flex min-w-0 flex-col gap-3 rounded-md border p-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><p className="break-words font-medium">{g.name}</p><p className="text-xs text-muted-foreground">{g.relationship || 'Relação não informada'} · {statusLabels[g.status] || g.status}</p><p className="text-xs text-muted-foreground">Período: {formatDate(g.valid_from)} até {formatDate(g.valid_until)}</p><p className="text-xs text-muted-foreground">{g.consent?.recorded ? 'Consentimento registrado' : 'Consentimento não registrado'}</p></div>{g.status === 'active' && <AlertDialog open={revoking?.id === g.id} onOpenChange={(open) => { setRevoking(open ? g : null); if (!open) { setReason(''); setError(''); } }}><AlertDialogTrigger asChild><Button type="button" variant="outline" aria-label={`Revogar ${g.name}`} className="w-full shrink-0 sm:w-auto">Revogar</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Revogar responsável</AlertDialogTitle><AlertDialogDescription>Esta ação mantém o histórico do episódio e exige uma justificativa.</AlertDialogDescription></AlertDialogHeader><div><Label htmlFor={`revoke-reason-${g.id}`}>Motivo da revogação</Label><Input id={`revoke-reason-${g.id}`} value={reason} onChange={(e) => setReason(e.target.value)} /></div>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction type="button" onClick={(event) => { event.preventDefault(); revoke(); }} disabled={busy}>Confirmar revogação</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}</div>)}
    {!adding && <Button type="button" disabled={!episodeId} onClick={() => setAdding(true)}>{active ? 'Substituir responsável' : 'Adicionar responsável'}</Button>}
    {adding && <form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="guardian-name">Nome do responsável</Label><Input id="guardian-name" required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></div><div><Label htmlFor="guardian-relation">Relação</Label><Input id="guardian-relation" required value={form.relationship} onChange={(e) => setForm({ ...form, relationship: e.target.value })} /></div><div><Label htmlFor="guardian-from">Início do período</Label><Input id="guardian-from" type="date" value={form.valid_from} onChange={(e) => setForm({ ...form, valid_from: e.target.value })} /></div><div><Label htmlFor="guardian-until">Fim do período</Label><Input id="guardian-until" type="date" value={form.valid_until} onChange={(e) => setForm({ ...form, valid_until: e.target.value })} /></div><label className="flex items-center gap-2 sm:col-span-2"><input type="checkbox" checked={form.consent_recorded} onChange={(e) => setForm({ ...form, consent_recorded: e.target.checked })} />Consentimento registrado</label>{active && <div className="sm:col-span-2"><Label htmlFor="replacement-reason">Motivo da substituição</Label><Input id="replacement-reason" required value={form.replacement_reason} onChange={(e) => setForm({ ...form, replacement_reason: e.target.value })} /></div>}<div className="flex flex-col gap-2 sm:flex-row"><Button disabled={busy}>{busy && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Salvar</Button><Button type="button" variant="ghost" onClick={() => setAdding(false)}>Cancelar</Button></div></form>}
    {error && !revoking && <p role="alert" className="text-sm text-destructive">{error}</p>}{success && <p role="status" className="text-sm text-green-700">{success}</p>}
  </CardContent></Card>;
}
