import {it,expect,vi}from'vitest';import{controlledRelease}from'./controlled-release.mjs';
const sha='a'.repeat(40),projectId='prj_zbE0dJoJrygKzMBq6nG9o7NdVV3H';
const evidence=()=>({sha,capturedAt:new Date().toISOString(),project:{id:projectId},candidateDeployment:{projectId,meta:{githubCommitSha:sha},readyState:'READY'},github:{checks:['verify','reconstruct','Vercel installation regression'].map(name=>({name,status:'completed',conclusion:'success'})),runs:[{status:'completed',conclusion:'success'}]}});
function setup(failure){const active={id:'dpl_new'};const calls=[];const provider={current:async()=>active.id,inspect:async id=>({projectId,meta:{githubCommitSha:sha},readyState:'READY',target:'production',url:id+'.vercel.app',alias:[]}),promote:async id=>{active.id=id;calls.push('promote');},rollback:async id=>{active.id=id;calls.push('rollback');}};const smoke=async(url,{stage})=>{calls.push(stage);if(stage===failure)throw Error('injected missing asset');};return{active,calls,args:{sha,evidence:evidence(),previous:'dpl_old',candidate:'dpl_new',provider,smoke,observe:async()=>({passed:true,durationMs:1800000,checks:31})}};}
it('validates the direct main deployment without promotion or fixed observation',async()=>{const s=setup();expect(await controlledRelease(s.args)).toMatchObject({passed:true});expect(s.calls).toEqual(['rollback-target','production']);expect(s.active.id).toBe('dpl_new');});
it('a different canonical deployment blocks verification without mutations',async()=>{const s=setup();s.active.id='dpl_other';await expect(controlledRelease(s.args)).rejects.toThrow('canonical');expect(s.calls).toEqual([]);});
it('post-promotion smoke failure restores and validates the previous synthetic deployment',async()=>{const s=setup('production');await expect(controlledRelease(s.args)).rejects.toThrow('injected');expect(s.calls).toEqual(['rollback-target','production','rollback','rollback']);expect(s.active.id).toBe('dpl_old');});
it('red checks block all provider mutations',async()=>{const s=setup();s.args.evidence.github.checks[0].conclusion='failure';s.args.provider.promote=vi.fn();await expect(controlledRelease(s.args)).rejects.toThrow('not green');expect(s.args.provider.promote).not.toHaveBeenCalled();});

it('a failure late in the observation window triggers the same automatic rollback',async()=>{const s=setup();s.args.observe=async()=>{throw Error('late runtime regression');};await expect(controlledRelease(s.args)).rejects.toThrow('late runtime');expect(s.active.id).toBe('dpl_old');expect(s.calls).toContain('rollback');});

it('an inaccessible recovery URL never rolls back the healthy live release',async()=>{const s=setup('rollback-target');await expect(controlledRelease(s.args)).rejects.toThrow('injected');expect(s.active.id).toBe('dpl_new');expect(s.calls).toEqual(['rollback-target']);});

it('invalid recovery metadata never mutates the canonical deployment',async()=>{const s=setup();const inspect=s.args.provider.inspect;s.args.provider.inspect=async id=>({...await inspect(id),readyState:id==='dpl_old'?'ERROR':'READY'});await expect(controlledRelease(s.args)).rejects.toThrow('Rollback target');expect(s.active.id).toBe('dpl_new');expect(s.calls).toEqual([]);});
