begin;

-- =====================================================
-- PHASE 23: Sprint 03 - Preferências de Lembrete
-- =====================================================
-- Objetivo:
-- Persistir preferências de lembrete por paciente (canal in-app e horários)
-- para suportar envio configurável nas próximas etapas.

create table if not exists public.patient_reminder_preferences (
  id bigint generated by default as identity primary key,
  patient_id uuid not null unique references public.user_profiles(id) on delete cascade,
  daily_log_enabled boolean not null default true,
  measurement_enabled boolean not null default true,
  daily_log_time time not null default '20:00',
  measurement_time time not null default '09:00',
  channel_in_app boolean not null default true,
  timezone text not null default 'America/Sao_Paulo',
  quiet_hours_start time null,
  quiet_hours_end time null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_patient_reminder_preferences_patient
  on public.patient_reminder_preferences(patient_id);

alter table public.patient_reminder_preferences enable row level security;

drop policy if exists patient_reminder_preferences_select_own on public.patient_reminder_preferences;
create policy patient_reminder_preferences_select_own
  on public.patient_reminder_preferences
  for select
  using (patient_id = auth.uid());

drop policy if exists patient_reminder_preferences_insert_own on public.patient_reminder_preferences;
create policy patient_reminder_preferences_insert_own
  on public.patient_reminder_preferences
  for insert
  with check (patient_id = auth.uid());

drop policy if exists patient_reminder_preferences_update_own on public.patient_reminder_preferences;
create policy patient_reminder_preferences_update_own
  on public.patient_reminder_preferences
  for update
  using (patient_id = auth.uid())
  with check (patient_id = auth.uid());

create or replace function public.set_patient_reminder_preferences_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_patient_reminder_preferences_updated_at on public.patient_reminder_preferences;
create trigger trg_patient_reminder_preferences_updated_at
before update on public.patient_reminder_preferences
for each row
execute function public.set_patient_reminder_preferences_updated_at();

comment on table public.patient_reminder_preferences is
  'Preferências de lembrete por paciente para canal in-app e horários.';

commit;
