
CREATE TABLE IF NOT EXISTS public.external_api_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_name TEXT NOT NULL,
    request_key TEXT NOT NULL UNIQUE,
    response_data JSONB NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS
ALTER TABLE public.external_api_cache ENABLE ROW LEVEL SECURITY;

-- Permitir acesso total para o service role (usado pelas Edge Functions)
CREATE POLICY "Service role can do everything" ON public.external_api_cache
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Criar índice para buscas rápidas
CREATE INDEX IF NOT EXISTS idx_external_api_cache_request_key ON public.external_api_cache(request_key);
CREATE INDEX IF NOT EXISTS idx_external_api_cache_expires_at ON public.external_api_cache(expires_at);
