begin;

-- =====================================================
-- PHASE 25: Sprint 04 - Foundation Automations + Lab Risk
-- =====================================================
-- Entregáveis desta etapa:
-- 1) communication_automations
-- 2) lab_risk_rules

create table if not exists public.communication_automations (
  id bigint generated by default as identity primary key,
  nutritionist_id uuid not null references public.user_profiles(id) on delete cascade,
  automation_key text not null,
  name text not null,
  description text null,
  trigger_event text not null,
  channel text not null default 'in_app' check (channel in ('in_app')),
  template_title text null,
  template_body text not null,
  is_active boolean not null default true,
  cooldown_hours int not null default 24 check (cooldown_hours >= 0 and cooldown_hours <= 720),
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(nutritionist_id, automation_key)
);

create index if not exists idx_communication_automations_nutritionist
  on public.communication_automations(nutritionist_id, is_active);

alter table public.communication_automations enable row level security;

drop policy if exists communication_automations_select_own on public.communication_automations;
create policy communication_automations_select_own
  on public.communication_automations
  for select
  using (nutritionist_id = auth.uid());

drop policy if exists communication_automations_insert_own on public.communication_automations;
create policy communication_automations_insert_own
  on public.communication_automations
  for insert
  with check (nutritionist_id = auth.uid());

drop policy if exists communication_automations_update_own on public.communication_automations;
create policy communication_automations_update_own
  on public.communication_automations
  for update
  using (nutritionist_id = auth.uid())
  with check (nutritionist_id = auth.uid());

drop policy if exists communication_automations_delete_own on public.communication_automations;
create policy communication_automations_delete_own
  on public.communication_automations
  for delete
  using (nutritionist_id = auth.uid());

create table if not exists public.lab_risk_rules (
  id bigint generated by default as identity primary key,
  nutritionist_id uuid null references public.user_profiles(id) on delete cascade,
  marker_key text not null,
  marker_label text not null,
  unit text null,
  low_threshold numeric null,
  high_threshold numeric null,
  risk_low text not null default 'none' check (risk_low in ('none','low','medium','high')),
  risk_high text not null default 'high' check (risk_high in ('none','low','medium','high')),
  is_active boolean not null default true,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_lab_risk_rules_scope
  on public.lab_risk_rules(nutritionist_id, marker_key, is_active);

create unique index if not exists uq_lab_risk_rules_global
  on public.lab_risk_rules(marker_key)
  where nutritionist_id is null;

create unique index if not exists uq_lab_risk_rules_custom
  on public.lab_risk_rules(nutritionist_id, marker_key)
  where nutritionist_id is not null;

alter table public.lab_risk_rules enable row level security;

drop policy if exists lab_risk_rules_select_scoped on public.lab_risk_rules;
create policy lab_risk_rules_select_scoped
  on public.lab_risk_rules
  for select
  using (nutritionist_id is null or nutritionist_id = auth.uid());

drop policy if exists lab_risk_rules_insert_own on public.lab_risk_rules;
create policy lab_risk_rules_insert_own
  on public.lab_risk_rules
  for insert
  with check (nutritionist_id = auth.uid());

drop policy if exists lab_risk_rules_update_own on public.lab_risk_rules;
create policy lab_risk_rules_update_own
  on public.lab_risk_rules
  for update
  using (nutritionist_id = auth.uid())
  with check (nutritionist_id = auth.uid());

drop policy if exists lab_risk_rules_delete_own on public.lab_risk_rules;
create policy lab_risk_rules_delete_own
  on public.lab_risk_rules
  for delete
  using (nutritionist_id = auth.uid());

create or replace function public.set_communication_automations_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_communication_automations_updated_at on public.communication_automations;
create trigger trg_communication_automations_updated_at
before update on public.communication_automations
for each row
execute function public.set_communication_automations_updated_at();

create or replace function public.set_lab_risk_rules_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_lab_risk_rules_updated_at on public.lab_risk_rules;
create trigger trg_lab_risk_rules_updated_at
before update on public.lab_risk_rules
for each row
execute function public.set_lab_risk_rules_updated_at();

insert into public.lab_risk_rules (
  nutritionist_id,
  marker_key,
  marker_label,
  unit,
  low_threshold,
  high_threshold,
  risk_low,
  risk_high,
  is_active
)
select
  null,
  seed.marker_key,
  seed.marker_label,
  seed.unit,
  seed.low_threshold,
  seed.high_threshold,
  seed.risk_low,
  seed.risk_high,
  true
from (
  values
    ('glicemia_jejum', 'Glicemia de Jejum', 'mg/dL', 70::numeric, 99::numeric, 'medium', 'high'),
    ('hdl', 'HDL', 'mg/dL', 40::numeric, null::numeric, 'medium', 'none'),
    ('ldl', 'LDL', 'mg/dL', null::numeric, 130::numeric, 'none', 'high'),
    ('triglicerideos', 'Triglicerídeos', 'mg/dL', null::numeric, 150::numeric, 'none', 'high')
) as seed(marker_key, marker_label, unit, low_threshold, high_threshold, risk_low, risk_high)
where not exists (
  select 1
  from public.lab_risk_rules lr
  where lr.nutritionist_id is null
    and lr.marker_key = seed.marker_key
);

commit;
