-- Pre-C6 stabilization: notifications and private progress/anthropometry photos.

-- ---------------------------------------------------------------------------
-- Notifications: the legacy helper returned uuid while notifications.id is
-- bigint, and exposed an arbitrary-recipient SECURITY DEFINER path to clients.
-- No frontend consumer uses the public wrapper; keep the primitive private and
-- service-role only.
-- ---------------------------------------------------------------------------

drop function if exists public.create_notification(uuid, text, text, text, text, jsonb);
drop function if exists private.create_notification(uuid, text, text, text, text, jsonb);

create function private.create_notification(
  p_user_id uuid,
  p_type text default 'info',
  p_title text default null,
  p_message text default null,
  p_link_url text default null,
  p_content jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_id bigint;
begin
  if not exists (select 1 from auth.users account where account.id = p_user_id) then
    return null;
  end if;

  insert into public.notifications (
    user_id, type, title, message, link_url, content, is_read
  ) values (
    p_user_id,
    coalesce(nullif(trim(p_type), ''), 'info'),
    p_title,
    p_message,
    p_link_url,
    jsonb_strip_nulls(
      coalesce(p_content, '{}'::jsonb) ||
      jsonb_build_object('title', p_title, 'message', p_message, 'link_url', p_link_url)
    ),
    false
  ) returning id into v_id;

  return v_id;
end;
$function$;

revoke all on function private.create_notification(uuid, text, text, text, text, jsonb)
  from public, anon, authenticated;
grant execute on function private.create_notification(uuid, text, text, text, text, jsonb)
  to service_role;

create table if not exists public.notification_events (
  id bigint generated by default as identity primary key,
  notification_id bigint not null,
  user_id uuid not null,
  actor_id uuid,
  event_type text not null check (event_type in ('read_state_changed', 'deleted')),
  snapshot jsonb not null,
  occurred_at timestamptz not null default now()
);

alter table public.notification_events enable row level security;
revoke all on public.notification_events from public, anon, authenticated;
grant select, insert on public.notification_events to service_role;
grant usage, select on sequence public.notification_events_id_seq to service_role;

create or replace function private.audit_notification_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if tg_op = 'DELETE' then
    insert into public.notification_events(
      notification_id,user_id,actor_id,event_type,snapshot
    ) values (
      old.id,old.user_id,auth.uid(),'deleted',to_jsonb(old)
    );
    return old;
  end if;

  if new.is_read is distinct from old.is_read then
    insert into public.notification_events(
      notification_id,user_id,actor_id,event_type,snapshot
    ) values (
      new.id,new.user_id,auth.uid(),'read_state_changed',to_jsonb(new)
    );
  end if;
  return new;
end;
$function$;

revoke all on function private.audit_notification_change()
  from public, anon, authenticated;

drop trigger if exists trg_audit_notification_change on public.notifications;
create trigger trg_audit_notification_change
after update or delete on public.notifications
for each row execute function private.audit_notification_change();

-- ---------------------------------------------------------------------------
-- Progress photos: preserve clinical history, bind every object to the care
-- episode, replace public URLs with short-lived signed URLs in the client, and
-- invalidate instead of hard-deleting rows or Storage objects.
-- ---------------------------------------------------------------------------

alter table public.progress_photos
  add column if not exists storage_path text,
  add column if not exists status text not null default 'active',
  add column if not exists invalidated_at timestamptz,
  add column if not exists invalidated_by uuid references public.user_profiles(id) on delete set null,
  add column if not exists invalidation_reason text;

update public.progress_photos
set storage_path = case
  when photo_url like '%/storage/v1/object/public/patient-photos/%'
    then split_part(photo_url, '/storage/v1/object/public/patient-photos/', 2)
  when photo_url like '%/storage/v1/object/sign/patient-photos/%'
    then split_part(split_part(photo_url, '/storage/v1/object/sign/patient-photos/', 2), '?', 1)
  when photo_url like 'patient-photos/%'
    then substring(photo_url from length('patient-photos/') + 1)
  else photo_url
end
where storage_path is null or trim(storage_path) = '';

update public.progress_photos photo
set care_episode_id = (
  select candidate.id
  from public.care_episodes candidate
  where candidate.patient_id = photo.patient_id
  order by
    case
      when photo.photo_date >= candidate.started_at::date
       and (candidate.ended_at is null or photo.photo_date <= candidate.ended_at::date)
      then 0 else 1
    end,
    (candidate.status = 'active') desc,
    candidate.started_at desc
  limit 1
)
where photo.care_episode_id is null;

alter table public.progress_photos
  drop constraint if exists progress_photos_status_check;
alter table public.progress_photos
  add constraint progress_photos_status_check
  check (status in ('active', 'invalidated'));

alter table public.progress_photos
  drop constraint if exists progress_photos_invalidation_check;
alter table public.progress_photos
  add constraint progress_photos_invalidation_check
  check (
    (status = 'active' and invalidated_at is null and invalidated_by is null and invalidation_reason is null)
    or
    (status = 'invalidated' and invalidated_at is not null and invalidated_by is not null and length(trim(invalidation_reason)) >= 3)
  );

create unique index if not exists progress_photos_storage_path_uidx
  on public.progress_photos(storage_path)
  where storage_path is not null;
create index if not exists progress_photos_episode_status_idx
  on public.progress_photos(care_episode_id, status, photo_date desc);

create table if not exists public.progress_photo_events (
  id bigint generated by default as identity primary key,
  progress_photo_id uuid not null references public.progress_photos(id) on delete restrict,
  patient_id uuid not null references public.user_profiles(id) on delete restrict,
  care_episode_id uuid references public.care_episodes(id) on delete restrict,
  actor_id uuid,
  event_type text not null,
  before_state jsonb,
  after_state jsonb,
  occurred_at timestamptz not null default now()
);

alter table public.progress_photo_events enable row level security;
revoke all on public.progress_photo_events from public, anon, authenticated;
grant select, insert on public.progress_photo_events to service_role;
grant usage, select on sequence public.progress_photo_events_id_seq to service_role;

create or replace function private.audit_progress_photo_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  insert into public.progress_photo_events (
    progress_photo_id, patient_id, care_episode_id, actor_id,
    event_type, before_state, after_state
  ) values (
    new.id,
    new.patient_id,
    new.care_episode_id,
    auth.uid(),
    case
      when tg_op = 'INSERT' then 'created'
      when old.status = 'active' and new.status = 'invalidated' then 'invalidated'
      else 'updated'
    end,
    case when tg_op = 'UPDATE' then to_jsonb(old) else null end,
    to_jsonb(new)
  );
  return new;
end;
$function$;

revoke all on function private.audit_progress_photo_change()
  from public, anon, authenticated;

drop trigger if exists trg_audit_progress_photo_change on public.progress_photos;
create trigger trg_audit_progress_photo_change
after insert or update on public.progress_photos
for each row execute function private.audit_progress_photo_change();

create or replace function private.protect_progress_photo_identity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if new.patient_id is distinct from old.patient_id
     or new.care_episode_id is distinct from old.care_episode_id
     or new.storage_path is distinct from old.storage_path
     or new.photo_url is distinct from old.photo_url
     or new.uploaded_by is distinct from old.uploaded_by then
    raise exception 'A identidade e o arquivo de uma foto clínica são imutáveis.' using errcode = '23514';
  end if;
  return new;
end;
$function$;

revoke all on function private.protect_progress_photo_identity()
  from public, anon, authenticated;

drop trigger if exists trg_protect_progress_photo_identity on public.progress_photos;
create trigger trg_protect_progress_photo_identity
before update on public.progress_photos
for each row execute function private.protect_progress_photo_identity();

drop policy if exists progress_photos_select on public.progress_photos;
drop policy if exists progress_photos_insert on public.progress_photos;
drop policy if exists progress_photos_update on public.progress_photos;
drop policy if exists progress_photos_delete on public.progress_photos;
drop policy if exists b2_episode_participant_select on public.progress_photos;
drop policy if exists b2_episode_isolation on public.progress_photos;

create policy progress_photos_participant_select
on public.progress_photos
for select to authenticated
using (
  exists (
    select 1 from public.care_episodes episode
    where episode.id = care_episode_id
      and episode.patient_id = patient_id
      and (
        episode.patient_id = (select auth.uid())
        or episode.nutritionist_id = (select auth.uid())
      )
  )
);

create policy progress_photos_active_episode_insert
on public.progress_photos
for insert to authenticated
with check (
  status = 'active'
  and storage_path is not null
  and exists (
    select 1 from public.care_episodes episode
    where episode.id = care_episode_id
      and episode.patient_id = patient_id
      and episode.status = 'active'
      and (
        episode.patient_id = (select auth.uid())
        or episode.nutritionist_id = (select auth.uid())
      )
  )
);

create policy progress_photos_active_metadata_update
on public.progress_photos
for update to authenticated
using (
  status = 'active'
  and exists (
    select 1 from public.care_episodes episode
    where episode.id = care_episode_id
      and (
        episode.patient_id = (select auth.uid())
        or episode.nutritionist_id = (select auth.uid())
      )
  )
)
with check (
  exists (
    select 1 from public.care_episodes episode
    where episode.id = care_episode_id
      and (
        episode.patient_id = (select auth.uid())
        or episode.nutritionist_id = (select auth.uid())
      )
  )
);

create or replace function public.invalidate_progress_photo(
  p_photo_id uuid,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_actor uuid := auth.uid();
  v_photo public.progress_photos%rowtype;
begin
  if v_actor is null then
    raise exception 'Autenticação obrigatória.' using errcode = '42501';
  end if;
  if length(trim(coalesce(p_reason, ''))) < 3 then
    raise exception 'Informe o motivo da invalidação.' using errcode = '22023';
  end if;

  select * into v_photo
  from public.progress_photos
  where id = p_photo_id
  for update;

  if not found then
    raise exception 'Foto não encontrada.' using errcode = 'P0002';
  end if;

  if not exists (
    select 1 from public.care_episodes episode
    where episode.id = v_photo.care_episode_id
      and (episode.patient_id = v_actor or episode.nutritionist_id = v_actor)
  ) then
    raise exception 'Você não tem permissão para invalidar esta foto.' using errcode = '42501';
  end if;

  if v_photo.status = 'invalidated' then
    return jsonb_build_object('success', true, 'already_invalidated', true, 'photo_id', v_photo.id);
  end if;

  update public.progress_photos
  set status = 'invalidated',
      invalidated_at = now(),
      invalidated_by = v_actor,
      invalidation_reason = trim(p_reason)
  where id = v_photo.id;

  return jsonb_build_object('success', true, 'already_invalidated', false, 'photo_id', v_photo.id);
end;
$function$;

revoke all on function public.invalidate_progress_photo(uuid, text)
  from public, anon;
grant execute on function public.invalidate_progress_photo(uuid, text)
  to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Private Storage policies. New object paths are:
-- patient_id/care_episode_id/progress_photos/file.ext
-- patient_id/care_episode_id/anthropometry/record_id/file.ext
-- ---------------------------------------------------------------------------

create or replace function private.can_access_patient_photo_object(p_name text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $function$
  select
    auth.uid() is not null
    and (
      exists (
        select 1
        from public.progress_photos photo
        join public.care_episodes episode on episode.id = photo.care_episode_id
        where photo.storage_path = p_name
          and photo.status = 'active'
          and (
            episode.patient_id = auth.uid()
            or episode.nutritionist_id = auth.uid()
          )
      )
      or exists (
        select 1
        from public.care_episodes episode
        where split_part(p_name, '/', 1) ~* '^[0-9a-f-]{36}$'
          and split_part(p_name, '/', 2) ~* '^[0-9a-f-]{36}$'
          and split_part(p_name, '/', 3) = 'anthropometry'
          and episode.patient_id = split_part(p_name, '/', 1)::uuid
          and episode.id = split_part(p_name, '/', 2)::uuid
          and (
            episode.patient_id = auth.uid()
            or episode.nutritionist_id = auth.uid()
          )
      )
    );
$function$;

create or replace function private.can_upload_patient_photo_object(p_name text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $function$
  select
    auth.uid() is not null
    and split_part(p_name, '/', 1) ~* '^[0-9a-f-]{36}$'
    and split_part(p_name, '/', 2) ~* '^[0-9a-f-]{36}$'
    and split_part(p_name, '/', 3) in ('progress_photos', 'anthropometry')
    and exists (
      select 1 from public.care_episodes episode
      where episode.patient_id = split_part(p_name, '/', 1)::uuid
        and episode.id = split_part(p_name, '/', 2)::uuid
        and episode.status = 'active'
        and (
          episode.patient_id = auth.uid()
          or episode.nutritionist_id = auth.uid()
        )
    );
$function$;

revoke all on function private.can_access_patient_photo_object(text)
  from public, anon;
revoke all on function private.can_upload_patient_photo_object(text)
  from public, anon;
grant execute on function private.can_access_patient_photo_object(text)
  to authenticated, service_role;
grant execute on function private.can_upload_patient_photo_object(text)
  to authenticated, service_role;

update storage.buckets
set public = false,
    file_size_limit = 5242880,
    allowed_mime_types = array[
      'image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif'
    ]::text[]
where id = 'patient-photos';

drop policy if exists "Access patient-photos" on storage.objects;
drop policy if exists "Users can view patient photos" on storage.objects;
drop policy if exists "Users can upload patient photos" on storage.objects;
drop policy if exists "Users can update patient photos" on storage.objects;
drop policy if exists "Users can delete own patient photos" on storage.objects;
drop policy if exists "Authenticated users can upload patient photos" on storage.objects;
drop policy if exists "Authenticated users can update patient photos" on storage.objects;
drop policy if exists "Authenticated users can delete patient photos" on storage.objects;
drop policy if exists patient_photos_private_select on storage.objects;
drop policy if exists patient_photos_private_insert on storage.objects;
drop policy if exists patient_photos_orphan_cleanup on storage.objects;

create policy patient_photos_private_select
on storage.objects for select to authenticated
using (
  bucket_id = 'patient-photos'
  and private.can_access_patient_photo_object(name)
);

create policy patient_photos_private_insert
on storage.objects for insert to authenticated
with check (
  bucket_id = 'patient-photos'
  and private.can_upload_patient_photo_object(name)
);

create policy patient_photos_orphan_cleanup
on storage.objects for delete to authenticated
using (
  bucket_id = 'patient-photos'
  and owner_id = auth.uid()::text
  and not exists (
    select 1 from public.progress_photos photo
    where photo.storage_path = name
  )
);
