import {act,renderHook,waitFor} from '@testing-library/react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {useGoalsPageController} from './useGoalsPageController';
const mocks=vi.hoisted(()=>({calculate:vi.fn(),patientId:null,active:vi.fn(),from:vi.fn(),capture:vi.fn(()=> 'technical-id')}));
vi.mock('react-router-dom',()=>({useNavigate:()=>()=>{}}));
vi.mock('@/hooks/useResolvedPatientId',()=>({useResolvedPatientId:()=>({patientId:mocks.patientId,paramValue:null})}));
vi.mock('@/components/ui/use-toast',()=>({useToast:()=>({toast:vi.fn()})}));
vi.mock('@/lib/customSupabaseClient',()=>({supabase:{from:mocks.from,auth:{getUser:async()=>({data:{user:null}})}}}));
vi.mock('@/infrastructure/observability/telemetry',()=>({captureOperationalError:mocks.capture}));
vi.mock('@/lib/supabase/clinical-impact-queries',()=>({logClinicalImpact:vi.fn()}));
vi.mock('@/lib/supabase/goals-queries',()=>({createGoal:vi.fn(),getPatientGoals:async()=>({data:[]}),getActiveGoal:mocks.active,updateGoalProgress:vi.fn(),completeGoal:vi.fn(),cancelGoal:vi.fn(),pauseGoal:vi.fn(),calculateGoalViability:mocks.calculate,calculateMinimumDeadline:()=>15,calculateIdealDeadline:()=>30}));
beforeEach(()=>{vi.useFakeTimers();vi.clearAllMocks();mocks.patientId=null;});
afterEach(()=>vi.useRealTimers());
it('discards late viability after input changes and stops loading when required input is cleared',async()=>{
 let finish;
 mocks.calculate.mockImplementation(()=>new Promise(resolve=>{finish=resolve;}));
 const {result}=renderHook(()=>useGoalsPageController());
 await act(async()=>{
   result.current.handleInputChange('initial_weight','80');
   result.current.handleInputChange('target_weight','75');
   result.current.handleInputChange('target_date','2027-01-01');
 });
 await act(async()=>vi.advanceTimersByTimeAsync(501));
 expect(result.current.loadingViability).toBe(true);
 await act(async()=>result.current.handleInputChange('target_weight',''));
 expect(result.current.loadingViability).toBe(false);
 await act(async()=>finish({score:5}));
 expect(result.current.viabilityPreview).toBeNull();
 await act(async()=>vi.advanceTimersByTimeAsync(501));
 expect(mocks.calculate).toHaveBeenCalledTimes(1);
});
it('does not open creation after a failed active-goal read and recovers on retry',async()=>{
 vi.useRealTimers();mocks.patientId='synthetic-patient';
 mocks.from.mockImplementation(()=>{const chain={};for(const method of ['select','eq'])chain[method]=()=>chain;chain.single=async()=>({data:{name:'Synthetic'}});return chain;});
 mocks.active.mockResolvedValueOnce({data:null,error:{status:403,message:'PRIVATE'}}).mockResolvedValueOnce({data:{id:'goal'},error:null});
 const {result}=renderHook(()=>useGoalsPageController());
 await waitFor(()=>expect(result.current.loading).toBe(false));
 expect(result.current.showForm).toBe(false);expect(result.current.loadError.kind).toBe('forbidden');
 expect(JSON.stringify(result.current.loadError)).not.toContain('PRIVATE');
 await act(async()=>result.current.loadData());
 expect(result.current.loadError).toBeNull();expect(result.current.activeGoal.id).toBe('goal');
});
