import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {readFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {createClient} from '@supabase/supabase-js';
import {randomUUID} from 'node:crypto';
import {seed} from './helpers/mealPlanFixture';
import {assertIsolatedRuntime,supabaseCommand,supabaseArgs} from '../scripts/qa/isolated-runtime.mjs';
assertIsolatedRuntime();
const fixture=JSON.parse(readFileSync('.backend-ci/browser-runtime/fixture.json'));
if(fixture.url!=='http://localhost:54321')throw Error('Disposable loopback stack required');
test.use({timezoneId:'America/Fortaleza'});
for(const width of [320,390,768,1024,1440])test(`patient reads the applied meals, portions and excluded alternative at ${width}px`,async({page})=>{
  const status=JSON.parse(execFileSync(supabaseCommand,supabaseArgs(['status','--workdir','.backend-ci','--output','json']),{encoding:'utf8',stdio:['pipe','pipe','pipe']}));
  if(status.API_URL!=='http://127.0.0.1:54321')throw Error('Disposable Auth required');
  const admin=createClient(status.API_URL,status.SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
  const identity=await admin.auth.admin.createUser({email:`${randomUUID()}@example.invalid`,password:fixture.password,email_confirm:true,user_metadata:{name:'QA Meal Module',user_type:'nutritionist',legal_version:'2026-10-01.2',terms_accepted:true,analytics_allowed:false}});
  expect(identity.error).toBeNull();
  const patient=identity.data.user.id;
  expect((await admin.auth.admin.updateUserById(patient,{email:`${patient}@example.invalid`,email_confirm:true})).error).toBeNull();
  const sample=seed(fixture.personas['nutritionist-a'].id,patient);
  const other=createClient(fixture.url,fixture.anonKey,{auth:{persistSession:false,autoRefreshToken:false}});
  expect((await other.auth.signInWithPassword({email:fixture.personas['patient-b'].email,password:fixture.password})).error).toBeNull();
  const denied=await other.from('meal_plans').select('id').eq('id',sample.plan);
  expect(denied.error).toBeNull();expect(denied.data).toEqual([]);
  await page.setViewportSize({width,height:900});
  await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill(`${sample.patient}@example.invalid`);await page.getByLabel('Senha',{exact:true}).fill(fixture.password);
  await page.getByRole('button',{name:'Entrar',exact:true}).click();await expect(page).toHaveURL(/\/patient$/);
  await expect(page.getByRole('button',{name:'Registrar Esta Refeição',exact:true})).toBeVisible();
  await expect(page.getByText('Nenhum plano alimentar ativo no momento.',{exact:true})).toHaveCount(0);
  await page.getByRole('link',{name:'Plano',exact:true}).click();
  await expect(page.getByText('Registrar Jantar',{exact:true})).toBeVisible();
  await expect(page.getByText('Registrar Café da Manhã',{exact:true})).toBeVisible();
  await page.waitForFunction(()=>[...document.querySelectorAll('.patient-page-content p')].every(node=>{
    for(let parent=node;parent;parent=parent.parentElement)if(Number(getComputedStyle(parent).opacity)<1)return false;
    return true;
  }));
  await page.getByRole('button',{name:'Ver plano alimentar',exact:true}).click();
  const dialog=page.getByRole('dialog',{name:'QA Plano completo com nome longo para testar leitura e navegação',exact:true});
  await expect(dialog.getByLabel('Totais diários do plano')).toContainText('100 kcal');
  await expect(dialog.getByText('QA Alimento do café',{exact:true})).toBeVisible();
  await expect(dialog.getByText('QA Porção alternativa',{exact:true})).toBeVisible();
  await expect(dialog.getByText('Refeição alternativa — não contabilizada nos totais.',{exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  const region=dialog.getByRole('region',{name:'Refeições e detalhes do plano'});
  await region.focus();await expect(region).toBeFocused();
  await page.keyboard.press('End');
  if(width===320)await expect.poll(()=>region.evaluate(node=>node.scrollTop)).toBeGreaterThan(0);
  await page.waitForFunction(()=>[...document.querySelectorAll('[role="dialog"]')].every(node=>Number(getComputedStyle(node).opacity)===1));
  const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
  await test.info().attach('accessibility',{body:JSON.stringify(axe.violations),contentType:'application/json'});
  expect(axe.violations.map(x=>({id:x.id,nodes:x.nodes.map(y=>y.target)}))).toEqual([]);
  await test.info().attach(`patient-prescription-${width}`,{body:await page.screenshot({fullPage:false}),contentType:'image/png'});
  await dialog.getByRole('button',{name:'Fechar plano',exact:true}).click();await page.reload();
  await page.getByRole('button',{name:'Ver plano alimentar',exact:true}).click();
  await expect(page.getByRole('dialog').getByLabel('Totais diários do plano')).toContainText('100 kcal');
});
