begin;

-- Sprint 06 - Etapa 1
-- No-show inteligente: extensao de appointments + trilha de notificacoes operacionais.

alter table public.appointments
  add column if not exists confirmation_status text not null default 'pending'
    check (confirmation_status in ('pending', 'confirmed', 'cancelled', 'no_response')),
  add column if not exists confirmation_channel text not null default 'in_app'
    check (confirmation_channel in ('in_app', 'whatsapp', 'sms', 'email', 'push', 'manual')),
  add column if not exists confirmation_requested_at timestamptz null,
  add column if not exists confirmed_at timestamptz null,
  add column if not exists cancelled_at timestamptz null,
  add column if not exists cancellation_reason text null,
  add column if not exists no_show_marked_at timestamptz null,
  add column if not exists attendance_marked_at timestamptz null,
  add column if not exists reminder_d1_scheduled_at timestamptz null,
  add column if not exists reminder_h2_scheduled_at timestamptz null,
  add column if not exists last_notification_at timestamptz null,
  add column if not exists no_show_score numeric(5,4) null
    check (no_show_score is null or (no_show_score >= 0 and no_show_score <= 1)),
  add column if not exists no_show_reason text null,
  add column if not exists no_show_metadata jsonb not null default '{}'::jsonb;

create index if not exists appointments_nutritionist_start_idx
  on public.appointments (nutritionist_id, start_time desc);

create index if not exists appointments_status_start_idx
  on public.appointments (status, start_time desc);

create index if not exists appointments_confirmation_status_start_idx
  on public.appointments (confirmation_status, start_time desc);

create table if not exists public.appointment_notifications (
  id bigint generated by default as identity primary key,
  appointment_id uuid not null references public.appointments(id) on delete cascade,
  nutritionist_id uuid not null references public.user_profiles(id) on delete cascade,
  patient_id uuid not null references public.user_profiles(id) on delete cascade,
  notification_type text not null
    check (notification_type in ('confirmation_d1', 'confirmation_h2', 'cancellation_followup', 'no_show_followup', 'manual_reprocess')),
  channel text not null default 'in_app'
    check (channel in ('in_app', 'whatsapp', 'sms', 'email', 'push', 'manual')),
  scheduled_for timestamptz not null,
  delivery_status text not null default 'pending'
    check (delivery_status in ('pending', 'processing', 'sent', 'failed', 'cancelled')),
  attempts int not null default 0 check (attempts >= 0),
  sent_at timestamptz null,
  cancelled_at timestamptz null,
  provider_message_id text null,
  error_message text null,
  last_error_at timestamptz null,
  payload jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists appointment_notifications_unique_schedule_idx
  on public.appointment_notifications (appointment_id, notification_type, scheduled_for);

create index if not exists appointment_notifications_queue_idx
  on public.appointment_notifications (delivery_status, scheduled_for asc, attempts asc);

create index if not exists appointment_notifications_nutritionist_idx
  on public.appointment_notifications (nutritionist_id, created_at desc);

create index if not exists appointment_notifications_patient_idx
  on public.appointment_notifications (patient_id, created_at desc);

create or replace function public.set_appointment_notifications_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_set_appointment_notifications_updated_at on public.appointment_notifications;
create trigger trg_set_appointment_notifications_updated_at
before update on public.appointment_notifications
for each row execute function public.set_appointment_notifications_updated_at();

alter table public.appointment_notifications enable row level security;

drop policy if exists "appointment_notifications_select_scoped" on public.appointment_notifications;
create policy "appointment_notifications_select_scoped"
on public.appointment_notifications
for select
to authenticated
using (
  nutritionist_id = auth.uid()
  or patient_id = auth.uid()
);

drop policy if exists "appointment_notifications_insert_own" on public.appointment_notifications;
create policy "appointment_notifications_insert_own"
on public.appointment_notifications
for insert
to authenticated
with check (nutritionist_id = auth.uid());

drop policy if exists "appointment_notifications_update_own" on public.appointment_notifications;
create policy "appointment_notifications_update_own"
on public.appointment_notifications
for update
to authenticated
using (nutritionist_id = auth.uid())
with check (nutritionist_id = auth.uid());

drop policy if exists "appointment_notifications_delete_own" on public.appointment_notifications;
create policy "appointment_notifications_delete_own"
on public.appointment_notifications
for delete
to authenticated
using (nutritionist_id = auth.uid());

commit;
