-- =============================================================
-- Phase 31 – Sprint 7: Message Templates Foundation
-- message_templates + template_dispatch_log + RLS
-- =============================================================

-- ─── message_templates ───────────────────────────────────────
create table if not exists public.message_templates (
    id              bigint generated by default as identity primary key,
    nutritionist_id uuid not null references public.user_profiles(id) on delete cascade,
    template_key    text not null,
    name            text not null,
    context         text not null default 'general'
                        check (context in ('general','low_adherence','goal_achieved','appointment_reminder',
                                           'no_show_followup','lab_alert','meal_plan_updated','post_consultation')),
    channel         text not null default 'in_app'
                        check (channel in ('in_app','whatsapp','sms','email','push','manual')),
    title_template  text null,
    body_template   text not null,
    variables       jsonb not null default '[]'::jsonb,
    is_active       boolean not null default true,
    use_count       int    not null default 0 check (use_count >= 0),
    last_used_at    timestamptz null,
    metadata        jsonb not null default '{}'::jsonb,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),
    constraint message_templates_key_unique unique (nutritionist_id, template_key)
);

create index if not exists message_templates_nutritionist_created_idx
    on public.message_templates (nutritionist_id, created_at desc);
create index if not exists message_templates_context_active_idx
    on public.message_templates (nutritionist_id, context, is_active);

-- updated_at trigger
create or replace function public.set_message_templates_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at = now();
    return new;
end;
$$;
drop trigger if exists trg_set_message_templates_updated_at on public.message_templates;
create trigger trg_set_message_templates_updated_at
    before update on public.message_templates
    for each row execute function public.set_message_templates_updated_at();

-- RLS
alter table public.message_templates enable row level security;

create policy "message_templates_select_own" on public.message_templates
    for select to authenticated using (nutritionist_id = auth.uid());

create policy "message_templates_insert_own" on public.message_templates
    for insert to authenticated with check (nutritionist_id = auth.uid());

create policy "message_templates_update_own" on public.message_templates
    for update to authenticated using (nutritionist_id = auth.uid())
    with check (nutritionist_id = auth.uid());

create policy "message_templates_delete_own" on public.message_templates
    for delete to authenticated using (nutritionist_id = auth.uid());


-- ─── template_dispatch_log ───────────────────────────────────
create table if not exists public.template_dispatch_log (
    id              bigint generated by default as identity primary key,
    template_id     bigint not null references public.message_templates(id) on delete cascade,
    nutritionist_id uuid   not null references public.user_profiles(id) on delete cascade,
    patient_id      uuid   not null references public.user_profiles(id) on delete cascade,
    channel         text   not null default 'in_app',
    trigger_event   text   null,
    rendered_title  text   null,
    rendered_body   text   not null,
    variables_used  jsonb  not null default '{}'::jsonb,
    delivery_status text   not null default 'sent'
                        check (delivery_status in ('sent','failed','pending')),
    error_message   text   null,
    metadata        jsonb  not null default '{}'::jsonb,
    created_at      timestamptz not null default now()
);

create index if not exists template_dispatch_log_template_created_idx
    on public.template_dispatch_log (template_id, created_at desc);
create index if not exists template_dispatch_log_nutritionist_created_idx
    on public.template_dispatch_log (nutritionist_id, created_at desc);
create index if not exists template_dispatch_log_patient_created_idx
    on public.template_dispatch_log (patient_id, created_at desc);

alter table public.template_dispatch_log enable row level security;

create policy "template_dispatch_log_select_scoped" on public.template_dispatch_log
    for select to authenticated
    using (nutritionist_id = auth.uid() or patient_id = auth.uid());

create policy "template_dispatch_log_insert_own" on public.template_dispatch_log
    for insert to authenticated with check (nutritionist_id = auth.uid());


-- ─── RPC: render_message_template ────────────────────────────
-- Renders title + body replacing {{var}} placeholders.
create or replace function public.render_message_template(
    p_template_id     bigint,
    p_patient_id      uuid,
    p_extra_variables jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_tpl         record;
    v_patient     record;
    v_title       text;
    v_body        text;
    v_vars        jsonb;
    v_key         text;
    v_val         text;
begin
    select * into v_tpl from public.message_templates where id = p_template_id;
    if not found then
        return jsonb_build_object('ok', false, 'reason', 'template_not_found');
    end if;

    select full_name, email into v_patient
    from public.user_profiles where id = p_patient_id;

    -- Build variable map
    v_vars := jsonb_build_object(
        'nome_paciente',  coalesce(v_patient.full_name, 'Paciente'),
        'email_paciente', coalesce(v_patient.email, ''),
        'data_hoje',      to_char(now() at time zone 'America/Sao_Paulo', 'DD/MM/YYYY')
    ) || coalesce(p_extra_variables, '{}'::jsonb);

    v_title := coalesce(v_tpl.title_template, '');
    v_body  := v_tpl.body_template;

    -- Replace placeholders
    for v_key, v_val in select key, value #>> '{}' from jsonb_each(v_vars) loop
        v_title := replace(v_title, '{{' || v_key || '}}', coalesce(v_val, ''));
        v_body  := replace(v_body,  '{{' || v_key || '}}', coalesce(v_val, ''));
    end loop;

    return jsonb_build_object(
        'ok',             true,
        'template_id',    v_tpl.id,
        'template_key',   v_tpl.template_key,
        'channel',        v_tpl.channel,
        'rendered_title', v_title,
        'rendered_body',  v_body,
        'variables_used', v_vars
    );
end;
$$;

grant execute on function public.render_message_template(bigint, uuid, jsonb) to authenticated;


-- ─── RPC: dispatch_message_template ──────────────────────────
create or replace function public.dispatch_message_template(
    p_template_id     bigint,
    p_patient_id      uuid,
    p_trigger_event   text   default null,
    p_extra_variables jsonb  default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_render        jsonb;
    v_actor         uuid := auth.uid();
    v_log_id        bigint;
    v_notification_id uuid;
    v_message       text;
    v_title         text;
begin
    if v_actor is null then
        return jsonb_build_object('ok', false, 'reason', 'unauthenticated');
    end if;

    -- Render template
    v_render := public.render_message_template(p_template_id, p_patient_id, p_extra_variables);
    if not (v_render->>'ok')::boolean then
        return v_render;
    end if;

    v_title   := v_render->>'rendered_title';
    v_message := v_render->>'rendered_body';

    -- Insert dispatch log
    insert into public.template_dispatch_log (
        template_id, nutritionist_id, patient_id, channel,
        trigger_event, rendered_title, rendered_body,
        variables_used, delivery_status
    ) values (
        p_template_id, v_actor, p_patient_id, v_render->>'channel',
        p_trigger_event, v_title, v_message,
        v_render->'variables_used', 'sent'
    ) returning id into v_log_id;

    -- Insert in-app notification for the patient
    if (v_render->>'channel') = 'in_app' or (v_render->>'channel') is null then
        insert into public.notifications (
            user_id, type, title, message, link_url, read_at
        ) values (
            p_patient_id,
            'template_dispatch',
            coalesce(nullif(v_title, ''), 'Mensagem do Nutricionista'),
            v_message,
            '/patient/home',
            null
        ) returning id into v_notification_id;
    end if;

    -- Increment use_count
    update public.message_templates
    set use_count    = use_count + 1,
        last_used_at = now()
    where id = p_template_id;

    return jsonb_build_object(
        'ok',          true,
        'log_id',      v_log_id,
        'rendered',    v_render
    );
end;
$$;

grant execute on function public.dispatch_message_template(bigint, uuid, text, jsonb) to authenticated;
