-- =============================================================
-- Phase 32 – Sprint 7: Consultation Checklists
-- consultation_checklists + RLS + RPC generate/update
-- =============================================================

-- ─── consultation_checklists ─────────────────────────────────
create table if not exists public.consultation_checklists (
    id              bigint generated by default as identity primary key,
    nutritionist_id uuid   not null references public.user_profiles(id) on delete cascade,
    patient_id      uuid   not null references public.user_profiles(id) on delete cascade,
    appointment_id  uuid   null references public.appointments(id) on delete set null,
    status          text   not null default 'pending'
                        check (status in ('pending','in_progress','completed','cancelled')),
    items           jsonb  not null default '[]'::jsonb,
    completed_items int    not null default 0 check (completed_items >= 0),
    total_items     int    not null default 0 check (total_items >= 0),
    completed_at    timestamptz null,
    metadata        jsonb  not null default '{}'::jsonb,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create index if not exists consultation_checklists_nutritionist_patient_idx
    on public.consultation_checklists (nutritionist_id, patient_id, created_at desc);
create index if not exists consultation_checklists_appointment_idx
    on public.consultation_checklists (appointment_id)
    where appointment_id is not null;
create index if not exists consultation_checklists_status_idx
    on public.consultation_checklists (nutritionist_id, status, created_at desc);

-- updated_at trigger
create or replace function public.set_consultation_checklists_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at = now();
    return new;
end;
$$;
drop trigger if exists trg_set_consultation_checklists_updated_at on public.consultation_checklists;
create trigger trg_set_consultation_checklists_updated_at
    before update on public.consultation_checklists
    for each row execute function public.set_consultation_checklists_updated_at();

-- RLS
alter table public.consultation_checklists enable row level security;

create policy "consultation_checklists_select_scoped" on public.consultation_checklists
    for select to authenticated
    using (nutritionist_id = auth.uid() or patient_id = auth.uid());

create policy "consultation_checklists_insert_own" on public.consultation_checklists
    for insert to authenticated with check (nutritionist_id = auth.uid());

create policy "consultation_checklists_update_scoped" on public.consultation_checklists
    for update to authenticated
    using (nutritionist_id = auth.uid() or patient_id = auth.uid())
    with check (nutritionist_id = auth.uid() or patient_id = auth.uid());

create policy "consultation_checklists_delete_own" on public.consultation_checklists
    for delete to authenticated using (nutritionist_id = auth.uid());


-- ─── RPC: generate_consultation_checklist ────────────────────
-- Auto-generates a pre-consultation checklist (5-10 prioritized items)
-- based on patient's clinical context.
create or replace function public.generate_consultation_checklist(
    p_nutritionist_id uuid,
    p_patient_id      uuid,
    p_appointment_id  uuid default null,
    p_extra_items     jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_actor           uuid := auth.uid();
    v_items           jsonb := '[]'::jsonb;
    v_item            jsonb;
    v_has_anamnesis   boolean := false;
    v_has_meal_plan   boolean := false;
    v_has_labs        boolean := false;
    v_has_antro       boolean := false;
    v_checklist_id    bigint;
    v_total           int;
    v_existing_id     bigint := null;
begin
    if v_actor is null then
        return jsonb_build_object('ok', false, 'reason', 'unauthenticated');
    end if;

    -- If a checklist already exists for this appointment, return it (allow re-open)
    if p_appointment_id is not null then
        select id into v_existing_id
        from public.consultation_checklists
        where appointment_id = p_appointment_id
          and patient_id = p_patient_id
        order by created_at desc
        limit 1;

        if v_existing_id is not null then
            return jsonb_build_object('ok', true, 'checklist_id', v_existing_id, 'reopened', true);
        end if;
    end if;

    -- Detect clinical context
    select exists(
        select 1 from public.anamnesis_records
        where patient_id = p_patient_id limit 1
    ) into v_has_anamnesis;

    select exists(
        select 1 from public.meal_plans
        where patient_id = p_patient_id and is_active = true limit 1
    ) into v_has_meal_plan;

    select exists(
        select 1 from public.lab_results
        where patient_id = p_patient_id limit 1
    ) into v_has_labs;

    select exists(
        select 1 from public.anthropometry_records
        where patient_id = p_patient_id limit 1
    ) into v_has_antro;

    -- Build prioritized item list
    -- Priority 1 (critical)
    v_items := v_items || jsonb_build_array(
        jsonb_build_object(
            'id', gen_random_uuid()::text,
            'label', 'Revisar objetivos e metas do paciente',
            'category', 'planning',
            'priority', 1,
            'done', false,
            'done_at', null
        )
    );

    if v_has_anamnesis then
        v_items := v_items || jsonb_build_array(
            jsonb_build_object(
                'id', gen_random_uuid()::text,
                'label', 'Verificar anamnese e histórico clínico',
                'category', 'clinical',
                'priority', 1,
                'done', false,
                'done_at', null
            )
        );
    else
        v_items := v_items || jsonb_build_array(
            jsonb_build_object(
                'id', gen_random_uuid()::text,
                'label', 'Preencher anamnese (primeira consulta)',
                'category', 'clinical',
                'priority', 1,
                'done', false,
                'done_at', null
            )
        );
    end if;

    -- Priority 2
    if v_has_meal_plan then
        v_items := v_items || jsonb_build_array(
            jsonb_build_object(
                'id', gen_random_uuid()::text,
                'label', 'Revisar aderência ao plano alimentar vigente',
                'category', 'nutrition',
                'priority', 2,
                'done', false,
                'done_at', null
            )
        );
    else
        v_items := v_items || jsonb_build_array(
            jsonb_build_object(
                'id', gen_random_uuid()::text,
                'label', 'Criar plano alimentar inicial',
                'category', 'nutrition',
                'priority', 2,
                'done', false,
                'done_at', null
            )
        );
    end if;

    if v_has_antro then
        v_items := v_items || jsonb_build_array(
            jsonb_build_object(
                'id', gen_random_uuid()::text,
                'label', 'Registrar novos dados antropométricos',
                'category', 'anthropometry',
                'priority', 2,
                'done', false,
                'done_at', null
            ),
            jsonb_build_object(
                'id', gen_random_uuid()::text,
                'label', 'Comparar evolução corporal com consulta anterior',
                'category', 'anthropometry',
                'priority', 2,
                'done', false,
                'done_at', null
            )
        );
    else
        v_items := v_items || jsonb_build_array(
            jsonb_build_object(
                'id', gen_random_uuid()::text,
                'label', 'Coletar dados antropométricos iniciais (peso, estatura, circunferências)',
                'category', 'anthropometry',
                'priority', 2,
                'done', false,
                'done_at', null
            )
        );
    end if;

    -- Priority 3
    if v_has_labs then
        v_items := v_items || jsonb_build_array(
            jsonb_build_object(
                'id', gen_random_uuid()::text,
                'label', 'Analisar exames laboratoriais recentes',
                'category', 'labs',
                'priority', 3,
                'done', false,
                'done_at', null
            )
        );
    end if;

    v_items := v_items || jsonb_build_array(
        jsonb_build_object(
            'id', gen_random_uuid()::text,
            'label', 'Avaliar ingestão hídrica e padrão de sono',
            'category', 'lifestyle',
            'priority', 3,
            'done', false,
            'done_at', null
        ),
        jsonb_build_object(
            'id', gen_random_uuid()::text,
            'label', 'Registrar recomendações e orientações pós-consulta',
            'category', 'planning',
            'priority', 3,
            'done', false,
            'done_at', null
        )
    );

    -- Merge extra items from caller
    if jsonb_array_length(coalesce(p_extra_items, '[]'::jsonb)) > 0 then
        v_items := v_items || p_extra_items;
    end if;

    -- Cap at 10 items
    if jsonb_array_length(v_items) > 10 then
        v_items := (
            select jsonb_agg(elem)
            from (
                select elem
                from jsonb_array_elements(v_items) elem
                order by (elem->>'priority')::int asc, random()
                limit 10
            ) sub
        );
    end if;

    v_total := jsonb_array_length(v_items);

    insert into public.consultation_checklists (
        nutritionist_id, patient_id, appointment_id,
        status, items, total_items, completed_items
    ) values (
        p_nutritionist_id, p_patient_id, p_appointment_id,
        'pending', v_items, v_total, 0
    ) returning id into v_checklist_id;

    return jsonb_build_object(
        'ok',           true,
        'checklist_id', v_checklist_id,
        'total_items',  v_total,
        'reopened',     false
    );
end;
$$;

grant execute on function public.generate_consultation_checklist(uuid, uuid, uuid, jsonb) to authenticated;


-- ─── RPC: update_checklist_item ──────────────────────────────
create or replace function public.update_checklist_item(
    p_checklist_id bigint,
    p_item_id      text,
    p_done         boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_actor       uuid := auth.uid();
    v_checklist   record;
    v_items       jsonb;
    v_new_items   jsonb := '[]'::jsonb;
    v_item        jsonb;
    v_completed   int  := 0;
    v_total       int;
    v_done_at     text;
    v_all_done    boolean;
begin
    if v_actor is null then
        return jsonb_build_object('ok', false, 'reason', 'unauthenticated');
    end if;

    select * into v_checklist
    from public.consultation_checklists
    where id = p_checklist_id
      and (nutritionist_id = v_actor or patient_id = v_actor);

    if not found then
        return jsonb_build_object('ok', false, 'reason', 'not_found_or_forbidden');
    end if;

    if v_checklist.status = 'completed' then
        return jsonb_build_object('ok', false, 'reason', 'already_completed');
    end if;

    v_items   := v_checklist.items;
    v_done_at := to_char(now() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"');

    -- Rebuild items array with updated item
    select jsonb_agg(
        case
            when (elem->>'id') = p_item_id then
                jsonb_set(jsonb_set(elem, '{done}', to_jsonb(p_done)),
                          '{done_at}', case when p_done then to_jsonb(v_done_at) else 'null'::jsonb end)
            else elem
        end
    ) into v_new_items
    from jsonb_array_elements(v_items) elem;

    -- Count completed
    select count(*) into v_completed
    from jsonb_array_elements(v_new_items) elem
    where (elem->>'done')::boolean = true;

    v_total    := jsonb_array_length(v_new_items);
    v_all_done := (v_completed = v_total and v_total > 0);

    update public.consultation_checklists
    set items           = v_new_items,
        completed_items = v_completed,
        status          = case when v_all_done then 'completed'
                               when v_completed > 0 then 'in_progress'
                               else 'pending' end,
        completed_at    = case when v_all_done then now() else null end
    where id = p_checklist_id;

    return jsonb_build_object(
        'ok',             true,
        'checklist_id',   p_checklist_id,
        'completed_items', v_completed,
        'total_items',    v_total,
        'all_done',       v_all_done
    );
end;
$$;

grant execute on function public.update_checklist_item(bigint, text, boolean) to authenticated;
