begin;

-- =====================================================
-- PHASE 26: Sprint 05 - Copilot + Meal Plan Versioning
-- =====================================================
-- Entregaveis desta etapa:
-- 1) clinical_recommendations
-- 2) meal_plan_versions

create table if not exists public.clinical_recommendations (
  id bigint generated by default as identity primary key,
  nutritionist_id uuid not null references public.user_profiles(id) on delete cascade,
  patient_id uuid not null references public.user_profiles(id) on delete cascade,
  recommendation_key text not null,
  source_module text not null default 'copilot_v1',
  title text not null,
  recommendation_text text not null,
  rationale text not null,
  confidence_score numeric(5,4) null check (confidence_score is null or (confidence_score >= 0 and confidence_score <= 1)),
  input_snapshot jsonb not null default '{}'::jsonb,
  output_snapshot jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending','accepted','dismissed','applied')),
  accepted_by uuid null references public.user_profiles(id) on delete set null,
  accepted_at timestamptz null,
  applied_at timestamptz null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_clinical_recommendations_nutritionist
  on public.clinical_recommendations(nutritionist_id, status, created_at desc);

create index if not exists idx_clinical_recommendations_patient
  on public.clinical_recommendations(patient_id, created_at desc);

create index if not exists idx_clinical_recommendations_key
  on public.clinical_recommendations(recommendation_key, created_at desc);

alter table public.clinical_recommendations enable row level security;

drop policy if exists clinical_recommendations_select_scoped on public.clinical_recommendations;
create policy clinical_recommendations_select_scoped
  on public.clinical_recommendations
  for select
  using (nutritionist_id = auth.uid() or patient_id = auth.uid());

drop policy if exists clinical_recommendations_insert_own on public.clinical_recommendations;
create policy clinical_recommendations_insert_own
  on public.clinical_recommendations
  for insert
  with check (nutritionist_id = auth.uid());

drop policy if exists clinical_recommendations_update_own on public.clinical_recommendations;
create policy clinical_recommendations_update_own
  on public.clinical_recommendations
  for update
  using (nutritionist_id = auth.uid())
  with check (nutritionist_id = auth.uid());

drop policy if exists clinical_recommendations_delete_own on public.clinical_recommendations;
create policy clinical_recommendations_delete_own
  on public.clinical_recommendations
  for delete
  using (nutritionist_id = auth.uid());

create or replace function public.set_clinical_recommendations_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_clinical_recommendations_updated_at on public.clinical_recommendations;
create trigger trg_clinical_recommendations_updated_at
before update on public.clinical_recommendations
for each row
execute function public.set_clinical_recommendations_updated_at();

create table if not exists public.meal_plan_versions (
  id bigint generated by default as identity primary key,
  meal_plan_id uuid not null references public.meal_plans(id) on delete cascade,
  nutritionist_id uuid not null references public.user_profiles(id) on delete cascade,
  patient_id uuid not null references public.user_profiles(id) on delete cascade,
  version_number int not null check (version_number > 0),
  change_reason text null,
  snapshot jsonb not null,
  is_rollback boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid null references public.user_profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(meal_plan_id, version_number)
);

create index if not exists idx_meal_plan_versions_plan
  on public.meal_plan_versions(meal_plan_id, version_number desc, created_at desc);

create index if not exists idx_meal_plan_versions_nutritionist
  on public.meal_plan_versions(nutritionist_id, created_at desc);

create index if not exists idx_meal_plan_versions_patient
  on public.meal_plan_versions(patient_id, created_at desc);

alter table public.meal_plan_versions enable row level security;

drop policy if exists meal_plan_versions_select_scoped on public.meal_plan_versions;
create policy meal_plan_versions_select_scoped
  on public.meal_plan_versions
  for select
  using (nutritionist_id = auth.uid() or patient_id = auth.uid());

drop policy if exists meal_plan_versions_insert_own on public.meal_plan_versions;
create policy meal_plan_versions_insert_own
  on public.meal_plan_versions
  for insert
  with check (nutritionist_id = auth.uid());

-- Versoes sao trilha historica: sem update/delete para manter rastreabilidade.

commit;
