-- =============================================================
-- Phase 33 – Sprint 8: Permissions + Conduct Suggestions + Impact Log
-- Entregáveis: permissions, conduct_suggestions, clinical_impact_log,
--             RPC evaluate_lab_goal_rules
-- =============================================================

-- ─── 1) permissions (mapeamento role -> módulo) ─────────────────
create table if not exists public.permissions (
    id          bigint generated by default as identity primary key,
    role        text not null check (role in ('nutritionist','patient','secretary','team','super_admin')),
    module      text not null check (module in (
        'goals','lab_results','energy','meal_plan','anthropometry',
        'food_diary','agenda','financial','anamnesis','clinical','alerts'
    )),
    can_view    boolean not null default true,
    can_edit    boolean not null default false,
    can_delete  boolean not null default false,
    metadata    jsonb not null default '{}'::jsonb,
    created_at  timestamptz not null default now(),
    constraint permissions_role_module_unique unique (role, module)
);

create index if not exists permissions_role_idx on public.permissions (role);

insert into public.permissions (role, module, can_view, can_edit, can_delete)
values
    ('nutritionist','goals',true,true,true),
    ('nutritionist','lab_results',true,true,true),
    ('nutritionist','energy',true,true,false),
    ('nutritionist','meal_plan',true,true,true),
    ('nutritionist','anthropometry',true,true,true),
    ('nutritionist','food_diary',true,true,false),
    ('nutritionist','agenda',true,true,true),
    ('nutritionist','financial',true,true,true),
    ('nutritionist','anamnesis',true,true,true),
    ('nutritionist','clinical',true,true,true),
    ('nutritionist','alerts',true,true,true),
    ('patient','goals',true,false,false),
    ('patient','lab_results',true,false,false),
    ('patient','energy',true,false,false),
    ('patient','meal_plan',true,false,false),
    ('patient','anthropometry',true,false,false),
    ('patient','food_diary',true,true,false),
    ('patient','agenda',true,false,false),
    ('patient','anamnesis',true,false,false),
    ('patient','clinical',true,false,false),
    ('patient','alerts',true,false,false),
    ('secretary','goals',true,false,false),
    ('secretary','lab_results',true,true,false),
    ('secretary','agenda',true,true,false),
    ('secretary','financial',true,true,false),
    ('team','goals',true,false,false),
    ('team','lab_results',true,true,false),
    ('team','agenda',true,true,false),
    ('super_admin','goals',true,true,true),
    ('super_admin','lab_results',true,true,true),
    ('super_admin','energy',true,true,true),
    ('super_admin','meal_plan',true,true,true),
    ('super_admin','anthropometry',true,true,true),
    ('super_admin','food_diary',true,true,true),
    ('super_admin','agenda',true,true,true),
    ('super_admin','financial',true,true,true),
    ('super_admin','anamnesis',true,true,true),
    ('super_admin','clinical',true,true,true),
    ('super_admin','alerts',true,true,true)
on conflict (role, module) do nothing;

alter table public.permissions enable row level security;

create policy "permissions_select_authenticated" on public.permissions
    for select to authenticated using (true);


-- ─── 2) clinical_impact_log (simulações de impacto) ────────────
create table if not exists public.clinical_impact_log (
    id              bigint generated by default as identity primary key,
    nutritionist_id uuid not null references public.user_profiles(id) on delete cascade,
    patient_id      uuid not null references public.user_profiles(id) on delete cascade,
    module          text not null check (module in ('goals','energy','meal_plan')),
    scenario        text not null check (scenario in ('weight_loss','weight_gain','maintenance')),
    initial_value   jsonb not null,
    simulated_value jsonb not null,
    impact_notes    text null,
    confidence_low  numeric null,
    confidence_high numeric null,
    was_applied     boolean not null default false,
    metadata        jsonb not null default '{}'::jsonb,
    created_at      timestamptz not null default now()
);

create index if not exists clinical_impact_log_nutritionist_created_idx
    on public.clinical_impact_log (nutritionist_id, created_at desc);
create index if not exists clinical_impact_log_patient_created_idx
    on public.clinical_impact_log (patient_id, created_at desc);

alter table public.clinical_impact_log enable row level security;

create policy "clinical_impact_log_select_own" on public.clinical_impact_log
    for select to authenticated using (nutritionist_id = auth.uid());
create policy "clinical_impact_log_insert_own" on public.clinical_impact_log
    for insert to authenticated with check (nutritionist_id = auth.uid());


-- ─── 3) conduct_suggestions (conduta por exames + objetivo) ────
create table if not exists public.conduct_suggestions (
    id              bigint generated by default as identity primary key,
    nutritionist_id uuid not null references public.user_profiles(id) on delete cascade,
    patient_id      uuid not null references public.user_profiles(id) on delete cascade,
    suggestion_key  text not null,
    title           text not null,
    rationale       text not null,
    suggested_conduct text null,
    lab_context     jsonb not null default '[]'::jsonb,
    goal_context    jsonb null,
    status          text not null default 'pending'
        check (status in ('pending','approved','rejected')),
    approved_by     uuid null references public.user_profiles(id) on delete set null,
    approved_at     timestamptz null,
    rejected_by     uuid null references public.user_profiles(id) on delete set null,
    rejected_at     timestamptz null,
    rejection_reason text null,
    metadata        jsonb not null default '{}'::jsonb,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create index if not exists conduct_suggestions_nutritionist_status_idx
    on public.conduct_suggestions (nutritionist_id, status, created_at desc);
create index if not exists conduct_suggestions_patient_idx
    on public.conduct_suggestions (patient_id, created_at desc);

create or replace function public.set_conduct_suggestions_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at = clock_timestamp();
    return new;
end;
$$;
drop trigger if exists trg_set_conduct_suggestions_updated_at on public.conduct_suggestions;
create trigger trg_set_conduct_suggestions_updated_at
    before update on public.conduct_suggestions
    for each row execute function public.set_conduct_suggestions_updated_at();

alter table public.conduct_suggestions enable row level security;

create policy "conduct_suggestions_select_own" on public.conduct_suggestions
    for select to authenticated using (nutritionist_id = auth.uid());
create policy "conduct_suggestions_insert_own" on public.conduct_suggestions
    for insert to authenticated with check (nutritionist_id = auth.uid());
create policy "conduct_suggestions_update_own" on public.conduct_suggestions
    for update to authenticated using (nutritionist_id = auth.uid())
    with check (nutritionist_id = auth.uid());


-- ─── 4) RPC evaluate_lab_goal_rules ─────────────────────────────
-- Avalia exames + meta do paciente e retorna sugestões de conduta.
create or replace function public.evaluate_lab_goal_rules(
    p_nutritionist_id uuid,
    p_patient_id      uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_actor         uuid := auth.uid();
    v_labs          jsonb;
    v_goal          jsonb;
    v_suggestions   jsonb := '[]'::jsonb;
    v_sug           jsonb;
    v_lab           record;
    v_normalized    text;
    v_lab_array     jsonb;
begin
    if v_actor is null then
        return jsonb_build_object('ok', false, 'reason', 'unauthenticated');
    end if;

    -- Buscar exames recentes anormais (usa cursor direto)
    v_labs := coalesce((
        select jsonb_agg(jsonb_build_object(
            'id', lr.id, 'test_name', lr.test_name, 'marker_key', lr.marker_key,
            'test_value', lr.test_value, 'status', lr.status, 'test_date', lr.test_date
        ))
        from public.lab_results lr
        where lr.patient_id = p_patient_id
          and lr.status in ('high','low')
        order by lr.test_date desc nulls last
        limit 20
    ), '[]'::jsonb);

    -- Buscar meta ativa
    select to_jsonb(pg.*) into v_goal
    from public.patient_goals pg
    where pg.patient_id = p_patient_id
      and pg.status = 'active'
    order by pg.created_at desc
    limit 1;

    -- Gerar sugestões por exame anormal
    for v_lab in
        select lr.id, lr.test_name, lr.marker_key, lr.test_value, lr.status, lr.test_date
        from public.lab_results lr
        where lr.patient_id = p_patient_id and lr.status in ('high','low')
        order by lr.test_date desc nulls last
        limit 20
    loop
        v_normalized := lower(replace(coalesce(nullif(trim(v_lab.marker_key), ''), v_lab.test_name, 'exame'), ' ', '_'));
        v_normalized := regexp_replace(v_normalized, '[^a-z0-9_]', '', 'g');
        if length(v_normalized) = 0 then v_normalized := 'exame'; end if;

        v_lab_array := jsonb_build_array(jsonb_build_object(
            'id', v_lab.id, 'test_name', v_lab.test_name, 'test_value', v_lab.test_value,
            'status', v_lab.status, 'test_date', v_lab.test_date
        ));

        if v_lab.status = 'high' then
            v_sug := jsonb_build_object(
                'suggestion_key', 'lab_high_' || v_normalized,
                'title', 'Exame acima da referência: ' || coalesce(v_lab.test_name, 'Exame'),
                'rationale', format('Valor %s acima do esperado. Ajustar conduta nutricional conforme protocolo.', v_lab.test_value),
                'suggested_conduct', 'Revisar plano alimentar e suplementação. Considerar retorno em 4-6 semanas.',
                'lab_context', v_lab_array,
                'goal_context', v_goal
            );
        else
            v_sug := jsonb_build_object(
                'suggestion_key', 'lab_low_' || v_normalized,
                'title', 'Exame abaixo da referência: ' || coalesce(v_lab.test_name, 'Exame'),
                'rationale', format('Valor %s abaixo do esperado. Avaliar ingestão e absorção.', v_lab.test_value),
                'suggested_conduct', 'Avaliar ingestão alimentar. Considerar suplementação se necessário.',
                'lab_context', v_lab_array,
                'goal_context', v_goal
            );
        end if;
        v_suggestions := v_suggestions || jsonb_build_array(v_sug);
    end loop;

    -- Sugestão combinada se tem meta + exames alterados
    if v_goal is not null and jsonb_array_length(v_labs) > 0 then
        v_sug := jsonb_build_object(
            'suggestion_key', 'goal_lab_combined',
            'title', 'Conduta: meta de peso + exames alterados',
            'rationale', 'Paciente com meta ativa e exames fora da faixa. Priorizar normalização dos marcadores.',
            'suggested_conduct', 'Ajustar déficit calórico de forma gradual. Monitorar exames em 4 semanas.',
            'lab_context', v_labs,
            'goal_context', v_goal
        );
        v_suggestions := v_suggestions || jsonb_build_array(v_sug);
    end if;

    return jsonb_build_object(
        'ok', true,
        'suggestions', v_suggestions,
        'lab_count', jsonb_array_length(v_labs),
        'has_goal', v_goal is not null
    );
end;
$$;

grant execute on function public.evaluate_lab_goal_rules(uuid, uuid) to authenticated;


-- ─── 5) RPC approve/reject conduct ─────────────────────────────
create or replace function public.approve_conduct_suggestion(
    p_suggestion_id bigint,
    p_actor_id      uuid default auth.uid()
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_row record;
begin
    if auth.uid() is null then
        return jsonb_build_object('ok', false, 'reason', 'unauthenticated');
    end if;

    select * into v_row from public.conduct_suggestions
    where id = p_suggestion_id and nutritionist_id = auth.uid();

    if not found then
        return jsonb_build_object('ok', false, 'reason', 'not_found');
    end if;

    if v_row.status != 'pending' then
        return jsonb_build_object('ok', false, 'reason', 'already_processed');
    end if;

    update public.conduct_suggestions
    set status = 'approved',
        approved_by = p_actor_id,
        approved_at = clock_timestamp(),
        rejected_by = null,
        rejected_at = null,
        rejection_reason = null
    where id = p_suggestion_id;

    return jsonb_build_object('ok', true, 'status', 'approved');
end;
$$;

create or replace function public.reject_conduct_suggestion(
    p_suggestion_id bigint,
    p_reason        text default null,
    p_actor_id      uuid default auth.uid()
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_row record;
begin
    if auth.uid() is null then
        return jsonb_build_object('ok', false, 'reason', 'unauthenticated');
    end if;

    select * into v_row from public.conduct_suggestions
    where id = p_suggestion_id and nutritionist_id = auth.uid();

    if not found then
        return jsonb_build_object('ok', false, 'reason', 'not_found');
    end if;

    if v_row.status != 'pending' then
        return jsonb_build_object('ok', false, 'reason', 'already_processed');
    end if;

    update public.conduct_suggestions
    set status = 'rejected',
        rejected_by = p_actor_id,
        rejected_at = clock_timestamp(),
        rejection_reason = p_reason,
        approved_by = null,
        approved_at = null
    where id = p_suggestion_id;

    return jsonb_build_object('ok', true, 'status', 'rejected');
end;
$$;

grant execute on function public.approve_conduct_suggestion(bigint, uuid) to authenticated;
grant execute on function public.reject_conduct_suggestion(bigint, text, uuid) to authenticated;
