-- CI-only schema gaps: eight tables exist in production but their CREATE is absent

-- from all 213 recorded migrations. Reconstructed from live metadata, no row data.

CREATE TABLE public."bug_reports" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "error_type" character varying(100) DEFAULT 'Error'::character varying,
  "error_message" text,
  "stack_trace" text,
  "route" text,
  "source_file" text,
  "line_number" integer,
  "column_number" integer,
  "user_id" uuid,
  "user_email" text,
  "user_name" text,
  "user_type" character varying(50),
  "user_agent" text,
  "bug_type" character varying(50) DEFAULT 'frontend'::character varying,
  "severity" character varying(20) DEFAULT 'error'::character varying,
  "console_log" jsonb DEFAULT '[]'::jsonb,
  "metadata" jsonb DEFAULT '{}'::jsonb,
  "component_stack" text,
  "is_resolved" boolean DEFAULT false,
  "resolved_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "bug_reports_pkey" PRIMARY KEY (id)
);

ALTER TABLE public."bug_reports" ENABLE ROW LEVEL SECURITY;

CREATE TABLE public."feed_tasks" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "nutritionist_id" uuid NOT NULL,
  "patient_id" uuid,
  "source_type" text NOT NULL,
  "source_id" text,
  "title" text NOT NULL,
  "description" text,
  "priority_score" integer DEFAULT 0 NOT NULL,
  "priority_reason" text,
  "status" text DEFAULT 'open'::text NOT NULL,
  "snooze_until" timestamp with time zone,
  "first_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
  "last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
  "resolved_at" timestamp with time zone,
  "resolved_by" uuid,
  "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "feed_tasks_pkey" PRIMARY KEY (id),
  CONSTRAINT "feed_tasks_status_check" CHECK ((status = ANY (ARRAY['open'::text, 'snoozed'::text, 'resolved'::text])))
);

ALTER TABLE public."feed_tasks" ENABLE ROW LEVEL SECURITY;

CREATE TABLE public."message_templates" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nutritionist_id" uuid,
  "template_key" text NOT NULL,
  "name" text NOT NULL,
  "context" text DEFAULT 'general'::text NOT NULL,
  "channel" text DEFAULT 'in_app'::text NOT NULL,
  "title_template" text,
  "body_template" text NOT NULL,
  "variables" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "use_count" integer DEFAULT 0 NOT NULL,
  "last_used_at" timestamp with time zone,
  "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "message_templates_channel_check" CHECK ((channel = ANY (ARRAY['in_app'::text, 'whatsapp'::text, 'sms'::text, 'email'::text, 'push'::text, 'manual'::text]))),
  CONSTRAINT "message_templates_context_check" CHECK ((context = ANY (ARRAY['general'::text, 'low_adherence'::text, 'goal_achieved'::text, 'appointment_reminder'::text, 'no_show_followup'::text, 'lab_alert'::text, 'meal_plan_updated'::text, 'post_consultation'::text]))),
  CONSTRAINT "message_templates_key_unique" UNIQUE (nutritionist_id, template_key),
  CONSTRAINT "message_templates_pkey" PRIMARY KEY (id),
  CONSTRAINT "message_templates_use_count_check" CHECK ((use_count >= 0))
);

ALTER TABLE public."message_templates" ENABLE ROW LEVEL SECURITY;

CREATE TABLE public."notification_rules" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "scope" text DEFAULT 'feed_priority'::text NOT NULL,
  "nutritionist_id" uuid,
  "rule_key" text NOT NULL,
  "weight" numeric DEFAULT 1 NOT NULL,
  "config" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "notification_rules_pkey" PRIMARY KEY (id)
);

ALTER TABLE public."notification_rules" ENABLE ROW LEVEL SECURITY;

CREATE TABLE public."nutritionist_patients" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "nutritionist_id" uuid NOT NULL,
  "patient_id" uuid NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "tags" text[] DEFAULT '{}'::text[],
  "app_settings" jsonb DEFAULT '{}'::jsonb,
  "plan_expires_at" date,
  "checkin_streak_current" integer DEFAULT 0,
  "checkin_streak_best" integer DEFAULT 0,
  "last_checkin_at" timestamp with time zone,
  "engagement_level" text DEFAULT 'new'::text,
  "xp_points" integer DEFAULT 0,
  "level_name" text DEFAULT 'Iniciante'::text,
  "onboarding_completed" boolean DEFAULT false,
  "status" text DEFAULT 'active'::text,
  CONSTRAINT "nutritionist_patients_engagement_level_check" CHECK ((engagement_level = ANY (ARRAY['new'::text, 'engaged'::text, 'at_risk'::text, 'inactive'::text]))),
  CONSTRAINT "nutritionist_patients_nutritionist_id_patient_id_key" UNIQUE (nutritionist_id, patient_id),
  CONSTRAINT "nutritionist_patients_pkey" PRIMARY KEY (id),
  CONSTRAINT "nutritionist_patients_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'active'::text, 'rejected'::text, 'ended'::text])))
);

ALTER TABLE public."nutritionist_patients" ENABLE ROW LEVEL SECURITY;

CREATE TABLE public."operational_observability_log" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nutritionist_id" uuid,
  "patient_id" uuid,
  "module" text NOT NULL,
  "operation" text NOT NULL,
  "event_type" text NOT NULL,
  "latency_ms" integer DEFAULT 0 NOT NULL,
  "error_message" text,
  "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "operational_observability_log_event_type_check" CHECK ((event_type = ANY (ARRAY['success'::text, 'error'::text]))),
  CONSTRAINT "operational_observability_log_latency_ms_check" CHECK ((latency_ms >= 0)),
  CONSTRAINT "operational_observability_log_module_check" CHECK ((module = ANY (ARRAY['feed'::text, 'meal_plan'::text, 'food_diary'::text, 'agenda'::text, 'system'::text]))),
  CONSTRAINT "operational_observability_log_pkey" PRIMARY KEY (id)
);

ALTER TABLE public."operational_observability_log" ENABLE ROW LEVEL SECURITY;

CREATE TABLE public."patient_module_sync_flags" (
  "patient_id" uuid NOT NULL,
  "anthropometry_updated_at" timestamp with time zone,
  "needs_energy_recalc" boolean DEFAULT false NOT NULL,
  "needs_meal_plan_review" boolean DEFAULT false NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "patient_module_sync_flags_pkey" PRIMARY KEY (patient_id)
);

ALTER TABLE public."patient_module_sync_flags" ENABLE ROW LEVEL SECURITY;

CREATE TABLE public."template_dispatch_log" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "template_id" bigint NOT NULL,
  "nutritionist_id" uuid NOT NULL,
  "patient_id" uuid NOT NULL,
  "channel" text DEFAULT 'in_app'::text NOT NULL,
  "trigger_event" text,
  "rendered_title" text,
  "rendered_body" text NOT NULL,
  "variables_used" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "delivery_status" text DEFAULT 'sent'::text NOT NULL,
  "error_message" text,
  "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "template_dispatch_log_delivery_status_check" CHECK ((delivery_status = ANY (ARRAY['sent'::text, 'failed'::text, 'pending'::text]))),
  CONSTRAINT "template_dispatch_log_pkey" PRIMARY KEY (id)
);

ALTER TABLE public."template_dispatch_log" ENABLE ROW LEVEL SECURITY;
