-- CI-only current template signatures used by July ALTER but first recorded CREATE is August.

-- Obsolete JSONB overloads are absent in current production and explicitly dropped in August.

SET check_function_bodies = false;

CREATE OR REPLACE FUNCTION public.create_diet_template(p_user_id uuid, p_name text, p_description text, p_tags text[], p_meals jsonb)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$declare v_id uuid;v_meal jsonb;v_meal_id uuid;v_food jsonb;begin if auth.uid()is null or p_user_id<>auth.uid()then raise exception using errcode='42501',message='template_owner_mismatch';end if;if length(coalesce(btrim(p_name),''))<3 or jsonb_typeof(coalesce(p_meals,'[]'::jsonb))<>'array'then raise exception using errcode='22023',message='invalid_diet_template_payload';end if;insert into public.diet_templates(user_id,name,description,tags,current_version)values(auth.uid(),btrim(p_name),nullif(btrim(p_description),''),coalesce(p_tags,'{}'::text[]),1)returning id into v_id;for v_meal in select value from jsonb_array_elements(coalesce(p_meals,'[]'::jsonb))loop insert into public.diet_template_meals(template_id,name,time,order_index)values(v_id,coalesce(nullif(btrim(v_meal->>'name'),''),'RefeiÃ§Ã£o'),nullif(v_meal->>'time','')::time,coalesce((v_meal->>'order_index')::integer,0))returning id into v_meal_id;for v_food in select value from jsonb_array_elements(coalesce(v_meal->'foods','[]'::jsonb))loop insert into public.diet_template_foods(meal_id,food_id,quantity,unit,observation,order_index)values(v_meal_id,(v_food->>'food_id')::uuid,(v_food->>'quantity')::numeric,coalesce(nullif(v_food->>'unit',''),'g'),nullif(v_food->>'observation',''),coalesce((v_food->>'order_index')::integer,0));end loop;end loop;insert into public.diet_template_versions(template_id,version,snapshot,change_reason,created_by)values(v_id,1,private.build_diet_template_snapshot(v_id),'CriaÃ§Ã£o do template',auth.uid());return v_id;end$function$;

CREATE OR REPLACE FUNCTION public.update_diet_template(p_template_id uuid, p_user_id uuid, p_name text, p_description text, p_tags text[], p_meals jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$declare v_current integer;v_meal jsonb;v_meal_id uuid;v_food jsonb;begin if auth.uid()is null or p_user_id<>auth.uid()then raise exception using errcode='42501',message='template_owner_mismatch';end if;if length(coalesce(btrim(p_name),''))<3 or jsonb_typeof(coalesce(p_meals,'[]'::jsonb))<>'array'then raise exception using errcode='22023',message='invalid_diet_template_payload';end if;select current_version into v_current from public.diet_templates where id=p_template_id and user_id=auth.uid()for update;if not found then raise exception using errcode='42501',message='template_not_found_or_forbidden';end if;insert into public.diet_template_versions(template_id,version,snapshot,change_reason,created_by)values(p_template_id,v_current,private.build_diet_template_snapshot(p_template_id),'Snapshot anterior Ã  ediÃ§Ã£o',auth.uid())on conflict(template_id,version)do nothing;delete from public.diet_template_meals where template_id=p_template_id;update public.diet_templates set name=btrim(p_name),description=nullif(btrim(p_description),''),tags=coalesce(p_tags,'{}'::text[]),current_version=v_current+1,updated_at=now()where id=p_template_id;for v_meal in select value from jsonb_array_elements(coalesce(p_meals,'[]'::jsonb))loop insert into public.diet_template_meals(template_id,name,time,order_index)values(p_template_id,coalesce(nullif(btrim(v_meal->>'name'),''),'RefeiÃ§Ã£o'),nullif(v_meal->>'time','')::time,coalesce((v_meal->>'order_index')::integer,0))returning id into v_meal_id;for v_food in select value from jsonb_array_elements(coalesce(v_meal->'foods','[]'::jsonb))loop insert into public.diet_template_foods(meal_id,food_id,quantity,unit,observation,order_index)values(v_meal_id,(v_food->>'food_id')::uuid,(v_food->>'quantity')::numeric,coalesce(nullif(v_food->>'unit',''),'g'),nullif(v_food->>'observation',''),coalesce((v_food->>'order_index')::integer,0));end loop;end loop;insert into public.diet_template_versions(template_id,version,snapshot,change_reason,created_by)values(p_template_id,v_current+1,private.build_diet_template_snapshot(p_template_id),'Template atualizado',auth.uid());end$function$;
