import {execFileSync} from 'node:child_process';
import {mkdirSync,writeFileSync,readFileSync,existsSync} from 'node:fs';
import {supabaseCommand,supabaseArgs,assertIsolatedRuntime} from './isolated-runtime.mjs';
if(process.env.NELLO_LOCAL_QA!=='isolated')throw Error('Explicit NELLO_LOCAL_QA=isolated required');
assertIsolatedRuntime();
const run=(command,args,options={})=>execFileSync(command,args,{stdio:'inherit',timeout:300000,...options});
const node=args=>run(process.execPath,args);
const sb=(args,options={})=>run(supabaseCommand,supabaseArgs(args),options);
const sql=input=>run('docker',['exec','-i','-e','PGPASSWORD=postgres','supabase_db_nello-reconstruction','psql','-X','-h','127.0.0.1','-U','supabase_admin','-d','postgres','-v','ON_ERROR_STOP=1'],{input,encoding:'utf8',stdio:['pipe','inherit','inherit']});
run('docker',['info','--format','{{.ServerVersion}}'],{timeout:15000});
if(!existsSync('.backend-ci'))node(['scripts/backend/prepare.mjs','--baseline-only']);
// Supabase start prints disposable credentials on stdout; keep them out of QA logs.
sb(['start','--workdir','.backend-ci','--exclude','studio,logflare,vector,imgproxy'],{timeout:1200000,stdio:['ignore','ignore','inherit']});
console.log('PASS: isolated Supabase services started');
node(['scripts/qa/edge-gateway-parity.mjs']);
sql(readFileSync('scripts/backend/provider-defaults.sql','utf8'));
const catalog=run('docker',['exec','-i','-e','PGPASSWORD=postgres','supabase_db_nello-reconstruction','psql','-X','-h','127.0.0.1','-U','postgres','-d','postgres','-t','-A','-v','ON_ERROR_STOP=1'],{input:readFileSync('scripts/backend/catalog.sql','utf8'),encoding:'utf8',stdio:['pipe','pipe','pipe'],maxBuffer:64*1024*1024});
mkdirSync('.backend-ci/local-results',{recursive:true});writeFileSync('.backend-ci/local-results/catalog.json',catalog);
node(['scripts/backend/compare-catalog.mjs','operations/backend/production-catalog.json','.backend-ci/local-results/catalog.json','.backend-ci/local-results/catalog-diff.json']);
run('docker',['pull','ghcr.io/supabase/postgres-meta:v0.96.6']);
run('docker',['tag','ghcr.io/supabase/postgres-meta:v0.96.6','public.ecr.aws/supabase/postgres-meta:v0.96.6']);
const types=sb(['gen','types','typescript','--local','--schema','public','--workdir','.backend-ci'],{encoding:'utf8',stdio:['ignore','pipe','pipe'],maxBuffer:16*1024*1024});
writeFileSync('.backend-ci/local-results/reconstructed.types.ts',types);
node(['scripts/backend/compare-types.mjs','src/lib/database.types.ts','.backend-ci/local-results/reconstructed.types.ts']);
node(['scripts/backend/snapshot-restore.mjs']);node(['scripts/backend/edge-boot-smoke.mjs']);node(['scripts/backend/forward-contracts.mjs']);
node(['scripts/backend/sql-matrix.mjs']);node(['scripts/backend/wave09-integrity.mjs']);node(['scripts/backend/wave10-calculations.mjs']);node(['scripts/backend/gate-injections.mjs']);node(['scripts/qa/browser-fixture.mjs']);
node(['scripts/qa/wave10-clinical-pdf.mjs']);
node(['scripts/qa/realtime-boundaries.mjs']);
node(['scripts/qa/auth-onboarding.mjs']);
node(['scripts/qa/edge-boundaries.mjs']);
node(['scripts/qa/edge-expiry.mjs']);
node(['scripts/qa/auth-captcha.mjs']);
node(['node_modules/vite/bin/vite.js','build']);node(['node_modules/vite/bin/vite.js','build','--config','e2e/qa-build.config.mjs']);node(['scripts/qa/css-gate-injection.mjs']);
node(['node_modules/playwright/cli.js','install','chromium']);node(['node_modules/playwright/cli.js','test',...process.argv.slice(2)]);
node(['scripts/qa/storage-uploads.mjs']);
const recording=process.argv.slice(2).some(arg=>arg.startsWith('--update-snapshots'));
writeFileSync('.backend-ci/local-results/result.json',JSON.stringify({passed:!recording,phase:recording?'baseline-recording':'validation',capturedAt:new Date().toISOString(),productionData:false},null,2));
console.log(recording?'Baselines recorded; visual comparison remains REQUIRED.':'PASS: complete isolated local Wave 02 pipeline');
