import { it, expect } from 'vitest';
import { assertSyntheticRecoveryIdentities } from './recovery-identities.mjs';
const id = index => `20000000-0000-4000-8000-${String(index).padStart(12, '0')}`;
const personas = Object.fromEntries(Array.from({ length: 9 }, (_, index) => [`QA-${index}`, { id:id(index),email:`persona-${index}@example.invalid` }]));
const accounts = () => Object.values(personas).map(persona => ({ ...persona }));
it('accepts the nine initial personas and exact UUID patients generated by the clinical journeys', () => {
  expect(assertSyntheticRecoveryIdentities(accounts(), personas)).toBe(9);
  expect(assertSyntheticRecoveryIdentities([...accounts(),{id:id(10),email:`${id(10)}@example.invalid`}],personas)).toBe(10);
});
it.each([
  ['real email', {id:id(10),email:'real@example.com'}],
  ['unregistered synthetic signup', {id:id(10),email:'unknown@example.invalid'}],
  ['UUID email from another identity', {id:id(10),email:`${id(11)}@example.invalid`}],
  ['invalid identity', {id:'invalid',email:'invalid@example.invalid'}],
])('refuses %s even in an isolated stack', (_, account) => {
  expect(() => assertSyntheticRecoveryIdentities([...accounts(),account],personas)).toThrow('recovery account');
});
it('refuses missing, replaced or duplicate registered personas', () => {
  expect(() => assertSyntheticRecoveryIdentities(accounts().slice(1),personas)).toThrow('inventory');
  const rows=accounts();rows[0].email=`${rows[0].id}@example.invalid`;
  expect(() => assertSyntheticRecoveryIdentities(rows,personas)).toThrow('persona missing');
  expect(() => assertSyntheticRecoveryIdentities([...accounts(),accounts()[0]],personas)).toThrow('inventory');
});
