import React from 'react';
import { render, screen, fireEvent, waitFor, within } from '@testing-library/react';
import { expect, it, vi } from 'vitest';
import MealPlanForm from './MealPlanForm';
vi.stubGlobal('ResizeObserver', class { observe() {} unobserve() {} disconnect() {} });
const mocks = vi.hoisted(() => ({ shadow: { ready: true, status: 'idle', recovery: null, queue: vi.fn(), flush: vi.fn().mockResolvedValue(true), discard: vi.fn().mockResolvedValue(true) } }));
vi.mock('@/hooks/useShadowDraft', () => ({ useShadowDraft: () => mocks.shadow }));
vi.mock('@/hooks/useMealPlanDraft', () => ({ useMealPlanDraft: () => ({ draftId: null, saveStatus: 'idle', existingDraft: null, flushPlanInfo: async () => true }) }));
vi.mock('@/lib/supabase/meal-plan-queries', () => ({ getReferenceValues: async () => ({ data: null }), simulateMealPlanPortionAdjustment: () => null }));
vi.mock('./ImportMealFromProtocolDialog', () => ({ default: () => null }));
vi.mock('./SubstitutionDialog', () => ({ default: () => null }));
vi.mock('./MacrosChart', () => ({ default: () => null }));
vi.mock('./FoodSelector', () => ({ default: props => props.isOpen ? <button onClick={() => props.onSelect({ id: 88, name: 'Alimento sintético', calories: 100 })}>Escolher alimento sintético</button> : null }));
vi.mock('@/components/nutrition', () => ({ PremiumPortionSelector: props => <input aria-label="Quantidade" value={props.value.quantity} onChange={event => props.onChange({ ...props.value, quantity: Number(event.target.value) })} /> }));

it('captures and restores the whole plan and unfinished meal/food editors after leaving the page', async () => {
    let saved;
    const session = { ready: true, status: 'saved', queue: value => { saved = structuredClone(value); }, flush: async () => true, discard: vi.fn().mockResolvedValue(true) };
    const props = { patientId: 'synthetic-patient', nutritionistId: 'synthetic-owner', session, initialData: { id: 55, updated_at: 'revision-1', name: 'Plano base', active_days: [], meals: [{ id: 10, name: 'Refeição já existente', foods: [{ id: 20, food: { name: 'Alimento já existente' }, food_id: 1, quantity: 100, calories: 100 }] }] }, onCancel: vi.fn() };
    const first = render(<React.StrictMode><MealPlanForm {...props} /></React.StrictMode>);
    fireEvent.change(screen.getByLabelText(/Nome do Plano/), { target: { value: 'Plano em andamento' } });
    fireEvent.click(screen.getByRole('button', { name: 'Nova Refeição', exact: true }));
    const mealDialog = await screen.findByRole('dialog', { name: 'Nova Refeição' });
    fireEvent.change(within(mealDialog).getByLabelText(/Observações/), { target: { value: 'Refeição ainda em preenchimento' } });
    fireEvent.click(within(mealDialog).getByRole('button', { name: 'Adicionar Alimento' }));
    const foodDialog = await screen.findByRole('dialog', { name: 'Adicionar Alimento' });
    fireEvent.click(within(foodDialog).getByRole('button', { name: 'Buscar Alimento' }));
    fireEvent.click(screen.getByText('Escolher alimento sintético'));
    fireEvent.change(within(foodDialog).getByLabelText('Quantidade'), { target: { value: '33' } });
    fireEvent.change(within(foodDialog).getByLabelText(/Observações/), { target: { value: 'Alimento ainda não adicionado' } });
    await waitFor(() => expect(saved.editor.state.foodEditor.state.notes).toBe('Alimento ainda não adicionado'));
    expect(saved.formData.name).toBe('Plano em andamento');
    expect(saved.meals[0].foods[0].food.name).toBe('Alimento já existente');
    expect(saved.editor.state.formData.notes).toBe('Refeição ainda em preenchimento');
    expect(saved.editor.state.foodEditor.state.portion.quantity).toBe(33);
    const snapshot = structuredClone(saved);
    first.unmount();
    render(<React.StrictMode><MealPlanForm {...props} restoredSession={snapshot} /></React.StrictMode>);
    const reopened = await screen.findByRole('dialog', { name: 'Adicionar Alimento' });
    await waitFor(() => expect(within(reopened).getByLabelText('Quantidade')).toHaveValue('33'));
    expect(within(reopened).getByLabelText(/Observações/)).toHaveValue('Alimento ainda não adicionado');
    expect(within(reopened).getByText('Alimento sintético')).toBeVisible();
    await waitFor(() => expect(saved.meals[0].foods[0].food.name).toBe('Alimento já existente'));
    expect(session.discard).not.toHaveBeenCalled();
});
