import React from 'react';
import { Link } from 'react-router-dom';
import { ChevronRight, Utensils, Plus, Download, FolderOpen, RefreshCw, ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { patientHubRoute } from '@/lib/utils/patientRoutes';

export default function MealPlanHeader({ patientId, patientSlugOrId, patientName, hasPlan, fetching, onNew, onImport, onExport, onRefresh, onBrowse }) {
    const hub = patientHubRoute({id:patientId,slug:patientSlugOrId},'nutrition');
    return <header className="space-y-3">
        <nav aria-label="Navegação estrutural" className="flex flex-wrap items-center gap-1.5 text-xs text-muted-foreground"><Link className="rounded hover:text-primary focus-visible:ring-2 focus-visible:ring-primary" to="/nutritionist/patients">Pacientes</Link><ChevronRight aria-hidden="true" className="h-3 w-3" /><Link className="max-w-full break-words rounded hover:text-primary focus-visible:ring-2 focus-visible:ring-primary" to={hub}>{patientName || 'Paciente'}</Link><ChevronRight aria-hidden="true" className="h-3 w-3" /><Link to={hub} className="rounded hover:text-primary focus-visible:ring-2 focus-visible:ring-primary">Nutrição</Link><ChevronRight aria-hidden="true" className="h-3 w-3" /><span aria-current="page" className="font-medium text-foreground">Plano alimentar</span></nav>
        <div className="flex flex-wrap items-start justify-between gap-5"><div className="min-w-0 flex-[1_1_18rem]"><h1 className="flex items-start gap-3 text-2xl font-bold uppercase tracking-wide sm:text-3xl"><Utensils aria-hidden="true" className="h-7 w-7 shrink-0 text-primary" /><span className="min-w-0 break-words [overflow-wrap:anywhere]">Plano alimentar</span></h1><p className="mt-2 max-w-xl text-sm leading-relaxed text-muted-foreground">Visualize o plano, ajuste refeições e acompanhe a análise nutricional.</p></div><div className="grid w-full grid-cols-2 gap-2 sm:flex sm:w-auto sm:max-w-full sm:flex-wrap"><Button variant="outline" size="sm" onClick={onImport} className="gap-2"><FolderOpen aria-hidden="true" className="h-4 w-4" />Importar modelo</Button>{hasPlan && <Button variant="outline" size="sm" onClick={onExport} className="gap-2"><Download aria-hidden="true" className="h-4 w-4" />Exportar PDF</Button>}<Button size="sm" onClick={onNew} className="col-span-2 row-start-1 gap-2 sm:order-last"><Plus aria-hidden="true" className="h-4 w-4" />Novo Plano</Button></div></div>
        <div className="flex flex-wrap items-center justify-between gap-2"><Link to={hub} className="inline-flex items-center gap-1 rounded text-xs text-muted-foreground hover:text-primary focus-visible:ring-2 focus-visible:ring-primary"><ArrowLeft className="h-3 w-3" />Voltar ao paciente</Link><div className="flex max-w-full flex-wrap gap-2">{onBrowse && <Button size="sm" variant="ghost" onClick={onBrowse} className="gap-2 text-xs text-muted-foreground"><FolderOpen aria-hidden="true" className="h-3.5 w-3.5" />Meus Planos</Button>}<Button variant="ghost" size="sm" disabled={fetching} onClick={onRefresh} className="gap-2 text-xs text-muted-foreground"><RefreshCw aria-hidden="true" className={`h-3.5 w-3.5 ${fetching ? 'animate-spin motion-reduce:animate-none' : ''}`} />{fetching ? 'Atualizando...' : 'Atualizar'}</Button></div></div>
    </header>;
}
