import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Target, ArrowRight, Info } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { energyComparison } from '@/lib/utils/mealPlanWorkspace';
import { roundedNutrition } from '@/lib/utils/mealPlanPresentation';
import { energyCalculationNeedsVentaReview } from '@/lib/utils/energy-planning';
import EnergyFormulaDetails from '@/components/energy/EnergyFormulaDetails';
import { harrisEquationLabel } from '@/lib/utils/harris-history';

function PlanTargetMonitor({ compact = false, targetCalories, currentCalories = 0, patientId, patientSlugOrId, energyCalculation = null }) {
    const navigate = useNavigate();
    const needsReview = energyCalculationNeedsVentaReview(energyCalculation);
    const comparison = needsReview ? null : energyComparison(currentCalories, targetCalories);
    const configure = () => navigate(`/nutritionist/patients/${patientSlugOrId ?? patientId}/energy-expenditure`);
    return <section aria-label="Plano e meta energética" className={`grid gap-x-5 rounded-2xl border border-primary/15 bg-white p-4 sm:p-5 ${compact ? "[&_h2]:text-base" : "md:grid-cols-[minmax(0,2fr)_minmax(0,1fr)]"}`}>
        <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-base font-semibold tracking-normal">{compact ? 'Meta energética' : 'Plano × meta energética'}</h2>{!compact && <p className="mt-1 text-sm text-muted-foreground">Compare a prescrição com o cálculo energético do paciente.</p>}</div><Button type="button" variant="ghost" size="sm" onClick={configure} className="gap-2 text-primary"><Target aria-hidden="true" className="h-4 w-4" />{comparison ? 'Ver cálculo' : 'Definir meta'}<ArrowRight aria-hidden="true" className="h-4 w-4" /></Button></div>
        {!comparison ? <p className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">{needsReview ? 'A meta VENTA histórica precisa de confirmação clínica antes de ser usada no plano.' : 'Meta energética não definida. Configure o cálculo para visualizar esta comparação.'}</p> : <div className="contents">
            <div className={`mt-4 min-w-0 ${compact ? "" : "md:col-start-1 md:row-start-2"}`}><div role="progressbar" aria-label="Relação da energia do plano com a meta" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.min(100, Math.max(0, comparison.percentage))} aria-valuetext={`${roundedNutrition(comparison.percentage)}% da meta`} className="h-3 overflow-hidden rounded-full bg-primary/10"><div className="h-full rounded-full bg-primary transition-[width] motion-reduce:transition-none" style={{ width: `${Math.min(100, Math.max(0, comparison.percentage))}%` }} /></div>
                <div className="mt-3 flex flex-wrap justify-between gap-3 text-sm"><div><p className="font-bold tabular-nums">{roundedNutrition(currentCalories)} kcal</p><p className="mt-1 text-xs text-muted-foreground">Energia prescrita</p></div><div className="text-right"><p className="font-bold tabular-nums">{roundedNutrition(targetCalories)} kcal</p><p className="mt-1 text-xs text-muted-foreground">Meta energética</p></div></div>
            </div><div className={`mt-4 rounded-xl bg-primary/5 p-4 ${compact ? "" : "md:col-start-2 md:row-start-1 md:row-span-3 md:mt-0"}`}><p className="text-xs font-medium text-muted-foreground">Diferença em relação à meta</p><p className="mt-1 text-2xl font-bold tabular-nums">{comparison.difference > 0 ? '+' : comparison.difference < 0 ? '−' : ''}{roundedNutrition(Math.abs(comparison.difference))} <span className="text-sm font-medium">kcal</span></p><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{comparison.difference === 0 ? 'A energia prescrita corresponde à meta.' : `${roundedNutrition(Math.abs(comparison.differencePercentage))}% ${comparison.difference < 0 ? 'abaixo' : 'acima'} da meta energética. A adequação depende da avaliação do nutricionista.`}</p></div>
        </div>}
        {comparison && energyCalculation && <details className={`mt-3 text-xs text-muted-foreground ${compact ? "" : "md:col-start-1 md:row-start-3"}`}><summary className="cursor-pointer font-medium"><Info aria-hidden="true" className="mr-1 inline h-3.5 w-3.5" />Origem da meta e detalhes do cálculo</summary><div className="mt-3 space-y-2"><p>Protocolo: {harrisEquationLabel(energyCalculation) || energyCalculation.tmb_protocol || energyCalculation.protocol || energyCalculation.protocol_code || 'Não informado'}</p>{(energyCalculation.tmb_result ?? energyCalculation.tmb) != null && <p>TMB registrada: {roundedNutrition(energyCalculation.tmb_result ?? energyCalculation.tmb)} kcal.</p>}{energyCalculation.activity_factor != null && <p>Fator de atividade: {energyCalculation.activity_factor}.</p>}{(energyCalculation.get_result ?? energyCalculation.get) != null && <p>GET registrado: {roundedNutrition(energyCalculation.get_result ?? energyCalculation.get)} kcal.</p>}<p>A meta exibida considera o planejamento energético registrado, quando disponível.</p><EnergyFormulaDetails plan={energyCalculation.output_snapshot?.calculation_details} /></div></details>}
    </section>;
}
export default React.memo(PlanTargetMonitor);
