import {useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight,History,Info,ExternalLink} from 'lucide-react';
import {Card,CardHeader,CardTitle,CardContent} from '@/components/ui/card';
import {Badge} from '@/components/ui/badge';
import {Button} from '@/components/ui/button';
import {Label} from '@/components/ui/label';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {useAdminSource} from '@/portals/admin/hooks/useAdminSource';
import AdminSourceStatus from './AdminSourceStatus';
import {SIGNALS,OUTCOMES,signalState,capacityComparison,sampleQualification,civilDate,intelligenceError,RUNBOOKS,FIELD_LABELS,MODULE_NAMES,FEATURE_STAGES} from '@/portals/admin/model/intelligence';
import {operationalDate} from '@/portals/admin/model/sourceState';
import {intelligenceMute,intelligenceHistory,intelligenceReleases,intelligenceHealth,intelligenceContinuity} from '@/features/admin/services/intelligenceService';

function MuteEditor({signal,onClose,onRefresh}) {
 const [reason,setReason]=useState(''),[hours,setHours]=useState('1'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [baseline,setBaseline]=useState(signal),[conflict,setConflict]=useState(false);const intent=useRef(null);
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{
  const payload={key:baseline.key,revision:baseline.revision,hours:Number(hours),reason};const fingerprint=JSON.stringify(payload);
  if(intent.current?.fingerprint!==fingerprint)intent.current={fingerprint,nonce:crypto.randomUUID()};
  const result=await intelligenceMute({...payload,nonce:intent.current.nonce});if(result.error)throw result.error;if(result.data?.success!==true)throw Error('mute_unconfirmed');await onRefresh();onClose();
 }catch(failure){setError(intelligenceError(failure));if(failure?.code==='PT409')setConflict(true);}finally{setBusy(false);}}
 async function refresh(){setBusy(true);try{const result=await onRefresh();const current=result.data?.signals.find(s=>s.key===baseline.key);if(!current)throw Error('signal_unconfirmed');setBaseline(current);setConflict(false);setError('');intent.current=null;}catch(failure){setError(intelligenceError(failure));}finally{setBusy(false);}}
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent className="data-[state=open]:!animate-none [&_button]:transition-none [&_button.bg-primary]:hover:bg-primary [&_.text-muted-foreground]:text-foreground [&_h2]:tracking-normal [&_h2]:leading-snug [&_h2]:[word-spacing:.08em] [&_button]:h-auto [&_button]:min-h-11 [&_button]:whitespace-normal max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>Silêncio do alerta interno</DialogTitle><DialogDescription className="text-foreground">{SIGNALS[signal.key].label}. A condição continua visível; o monitor externo e o Sentry permanecem ativos. Uma nova ocorrência remove o silêncio anterior.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4">
 {error&&<p role="alert" className="text-sm text-destructive">{error}</p>}{conflict&&<Button type="button" variant="outline" disabled={busy} onClick={()=>void refresh()}>Atualizar contexto preservando motivo</Button>}
 <div className="space-y-2"><Label htmlFor="signal-hours">Duração</Label><select id="signal-hours" className="h-11 w-full rounded-md border bg-background px-3" value={hours} onChange={e=>setHours(e.target.value)} disabled={busy}>{[[0,'Remover silêncio'],[1,'Uma hora'],[6,'Seis horas'],[24,'24 horas']].map(([n,label])=><option key={n} value={n} disabled={n>0&&!baseline.active}>{label}</option>)}</select></div>
 <div className="space-y-2"><Label htmlFor="signal-reason">Motivo do silêncio ou reativação</Label><Textarea id="signal-reason" value={reason} onChange={e=>setReason(e.target.value)} minLength={10} maxLength={500} required disabled={busy}/></div><DialogFooter className="gap-2"><Button type="button" variant="outline" onClick={onClose} disabled={busy}>Cancelar</Button><Button disabled={busy||conflict}>{busy?'Confirmando…':'Confirmar alteração'}</Button></DialogFooter></form></DialogContent></Dialog>;
}
export function IntelligencePriorities({data,onRefresh}) {
 const [editing,setEditing]=useState(null);
 const ordered=[...(data?.signals||[])].sort((a,b)=>Number(b.active)-Number(a.active));
 const activation=data?sampleQualification(data.product.activation.activated,data.product.activation.eligible):null;
 const returning=data?sampleQualification(data.product.return.returned,data.product.return.eligible):null;
 return <div className="space-y-5">
  <div className="grid gap-4 lg:grid-cols-2">{ordered.map(signal=>{const definition=SIGNALS[signal.key];const state=signalState(signal);return <Card key={signal.key} className="min-w-0 rounded-2xl"><CardHeader className="space-y-3"><div className="flex flex-wrap items-start justify-between gap-2"><CardTitle className="text-base tracking-normal">{definition.label}</CardTitle><Badge variant={state.state==='active'&&definition.severity==='high'?'destructive':'outline'}>{state.label}</Badge></div></CardHeader><CardContent className="space-y-3"><p className="text-2xl font-semibold tabular-nums">{signal.value.toLocaleString('pt-BR')} <span className="text-sm font-normal text-muted-foreground">{definition.unit}</span></p><p className="text-sm">{definition.next}</p><p className="text-xs text-muted-foreground">Regra: {definition.rule}</p><p className="text-xs text-muted-foreground">Fonte: {definition.source} · avaliada em {operationalDate(signal.evaluated_at)}</p>{state.state==='muted'&&<p className="text-xs font-medium">Silêncio até {operationalDate(signal.muted_until)}</p>}<div className="flex flex-wrap gap-2"><Button asChild variant="outline"><Link to={definition.route}>Conferir origem<ArrowRight className="ml-2 h-4 w-4"/></Link></Button>{data.can_write&&(signal.active||signal.muted_until)&&<Button variant="ghost" onClick={()=>setEditing(signal)}>Gerenciar silêncio</Button>}</div></CardContent></Card>;})}</div>
  <Card className="rounded-2xl"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Info className="h-5 w-5"/>O que os dados permitem concluir</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p>Ativação: {activation?.ratio||'Consulta pendente'}. {activation?.label}</p><p>Retorno: {returning?.ratio||'Consulta pendente'}. {returning?.label}</p><p>Coortes anteriores ao início da captura não têm cobertura histórica completa. Confirmações no banco e capturas consentidas usam populações diferentes; não são subtraídas para estimar perda.</p><Button asChild variant="outline"><Link to="/admin/analytics">Investigar uso e valor</Link></Button></CardContent></Card>
  <details className="rounded-xl border p-4"><summary className="cursor-pointer text-sm font-medium">Política dos alertas · intelligence-v1</summary><p className="mt-3 text-sm text-muted-foreground">Uma condição mantém um único grupo por regra; novas leituras não criam novos alertas. Resolução e reabertura ficam registradas. Silêncio de uma, seis ou 24 horas exige motivo. Este painel é avaliado ao ser consultado, a cada dois minutos enquanto aberto; não substitui o monitor externo nem envia notificações adicionais.</p></details>
  <details className="rounded-xl border p-4"><summary className="cursor-pointer text-sm font-medium">Histórico recente dos alertas internos</summary><ol className="mt-3 space-y-3">{data?.signal_events.map(e=><li key={e.id} className="text-sm"><strong>{SIGNALS[e.signal_key].label}</strong><p className="mt-1">{e.reason}</p>{e.muted_until&&<p className="text-xs">Silêncio registrado até {operationalDate(e.muted_until)}</p>}<p className="text-xs text-muted-foreground">{operationalDate(e.created_at)} · ocorrência {e.episode}</p></li>)}</ol></details>
  {editing&&data?.can_write&&<MuteEditor signal={editing} onClose={()=>setEditing(null)} onRefresh={onRefresh}/>}
 </div>;
}
export function IntelligenceRecordCard({entry,canWrite,onEdit,onHistory}) {
 const p=entry.payload;const capacity=entry.kind==='capacity'?capacityComparison(p):null;
 const number=value=>value.toLocaleString('pt-BR',{maximumFractionDigits:2});
 return <Card className="min-w-0 rounded-2xl"><CardHeader><div className="flex flex-wrap items-start justify-between gap-2"><CardTitle className="break-words text-base tracking-normal">{p.title||`${p.provider} · ${p.resource}`}</CardTitle><Badge variant="outline">{entry.kind==='decision'?OUTCOMES[p.outcome]:'Registro manual'}</Badge></div><p className="text-xs text-muted-foreground">Atualizado em {operationalDate(entry.updated_at)} · versão {entry.revision}</p></CardHeader><CardContent className="space-y-3 text-sm">
 {entry.kind==='decision'&&<><p className="break-words"><strong>Evidência:</strong> {p.evidence}</p><p className="break-words"><strong>Ação:</strong> {p.action}</p><p className="break-words"><strong>Resultado esperado:</strong> {p.expected}</p><p><strong>Revisão:</strong> {civilDate(p.review_on)}</p>{p.result&&<p className="break-words"><strong>Resultado observado:</strong> {p.result}</p>}<p className="text-xs text-muted-foreground">Resultado observado não demonstra causalidade.</p></>}
 {entry.kind==='feature'&&<><p><strong>Etapa declarada:</strong> {FEATURE_STAGES[p.stage]}</p><p className="break-all">Identificador: {p.feature_key}</p><p>Módulo: {MODULE_NAMES[p.module]} · revisão em {civilDate(p.review_on)}</p><p className="break-words"><strong>Escopo:</strong> {p.scope}</p><p className="break-words"><strong>Justificativa:</strong> {p.rationale}</p><p className="text-xs text-muted-foreground">Inventário manual. Não altera flags, acesso ou funcionamento do produto.</p></>}
 {entry.kind==='change'&&<><p className="break-words">{p.detail}</p><p>Ocorrência: {operationalDate(p.occurred_at)} · módulo {MODULE_NAMES[p.module]||'Outro'}</p><p className="break-all">Commit: {p.release||'Não informado'}</p><p className="text-xs text-muted-foreground">Registro manual de {({release:'release',configuration:'configuração',incident:'incidente'})[p.change_kind]}; não certifica implantação ou resolução.</p></>}
 {capacity&&<><p className="text-2xl font-semibold">{number(p.used)} <span className="text-sm font-normal">{p.unit}</span></p><p>{capacity.label}{p.limit!==null?` · ${number(p.limit)} ${p.unit}`:''}</p>{capacity.percentage!==null&&<><div role="progressbar" aria-label="Uso em relação ao limite declarado" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.min(100,Math.round(capacity.percentage))} aria-valuetext={`${number(capacity.percentage)}% do limite declarado`} className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary" style={{width:`${Math.min(100,capacity.percentage)}%`}}/></div><p>{number(capacity.percentage)}% do limite declarado</p></>}<p>Custo: {p.cost===null?'Não informado':new Intl.NumberFormat('pt-BR',{style:'currency',currency:p.currency}).format(p.cost)}</p><p>Período: {civilDate(p.period_start)} a {civilDate(p.period_end)} · medição em {civilDate(p.measured_on)}</p><p className="break-words"><strong>Fonte declarada:</strong> {p.source_note}</p><p className="text-xs text-muted-foreground">Fotografia manual deste período. Não é quota atual automática ou previsão de esgotamento. Moedas e unidades não são somadas.</p></>}
 <div className="flex flex-wrap gap-2">{canWrite&&<Button variant="outline" onClick={()=>onEdit(entry)}>Revisar registro</Button>}<Button variant="ghost" onClick={()=>onHistory(entry)}><History className="mr-2 h-4 w-4"/>Histórico</Button></div>
 </CardContent></Card>;
}
export function IntelligenceRecordHistory({entry,onClose}) {
 const [page,setPage]=useState(1);const query=useAdminSource(['intelligence-history',entry.id,page],()=>intelligenceHistory(entry.id,page));
 return <Dialog open onOpenChange={open=>{if(!open)onClose();}}><DialogContent className="data-[state=open]:!animate-none [&_button]:transition-none [&_button.bg-primary]:hover:bg-primary [&_.text-muted-foreground]:text-foreground [&_h2]:tracking-normal [&_h2]:leading-snug [&_h2]:[word-spacing:.08em] [&_button]:h-auto [&_button]:min-h-11 [&_button]:whitespace-normal max-h-[90dvh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>Histórico do registro</DialogTitle><DialogDescription className="text-foreground">{entry.payload.title||entry.payload.resource}. Versões anteriores permanecem consultáveis; este histórico não restaura dados clínicos.</DialogDescription></DialogHeader><AdminSourceStatus query={query} queryOnly/><ol className="space-y-4">{query.data?.items.map(item=><li key={item.id} className="rounded-lg border p-3 text-sm"><p className="font-medium">Versão {item.revision} · {operationalDate(item.created_at)}</p><p className="mt-2 break-words">{item.reason}</p><details className="mt-2"><summary className="cursor-pointer">Dados desta versão</summary><dl className="mt-2 space-y-2">{Object.entries(item.payload).map(([key,value])=><div key={key}><dt className="text-xs text-muted-foreground">{FIELD_LABELS[key]||key}</dt><dd className="break-words">{value===null?'Não informado':String(value)}</dd></div>)}</dl></details></li>)}</ol><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={page===1||query.isFetching} onClick={()=>setPage(n=>n-1)}>Mais recentes</Button><Button variant="outline" disabled={!query.data||page*20>=query.data.total||query.isFetching} onClick={()=>setPage(n=>n+1)}>Mais antigas</Button></div></DialogContent></Dialog>;
}
export function IntelligenceReleaseTimeline(){
 const [cursors,setCursors]=useState([null]);const cursor=cursors.at(-1);const query=useAdminSource(['intelligence-releases',cursor],()=>intelligenceReleases(cursor));
 return <Card className="rounded-2xl"><CardHeader><CardTitle className="text-lg">Releases registradas no Sentry</CardTitle><p className="text-sm text-muted-foreground">Metadados oficiais do projeto. A criação de uma release no Sentry não certifica deploy, disponibilidade ou melhora do produto.</p></CardHeader><CardContent className="space-y-4"><AdminSourceStatus query={query} queryOnly/>{query.data?.state==='not_configured'?<p>Leitura de releases não configurada.</p>:query.data?.items.length===0?<p>Nenhuma release com SHA reconhecido foi retornada nesta página.</p>:<ol className="space-y-3">{query.data?.items.map(r=><li key={r.version} className="rounded-lg border p-3 text-sm"><p className="break-all font-mono">{r.version}</p><p className="mt-1 text-xs text-muted-foreground">Registrada em {operationalDate(r.created_at)}</p></li>)}</ol>}{query.data?.omitted>0&&<p className="text-xs text-muted-foreground">{query.data.omitted} versões com outro formato foram omitidas; não são tratadas como SHA de deploy.</p>}<div className="flex flex-wrap gap-2"><Button variant="outline" disabled={cursors.length===1||query.isFetching} onClick={()=>setCursors(v=>v.slice(0,-1))}>Mais recentes</Button><Button variant="outline" disabled={!query.data?.next_cursor||query.isFetching||cursors.includes(query.data?.next_cursor)} onClick={()=>setCursors(v=>[...v,query.data.next_cursor])}>Mais antigas</Button><Button asChild variant="ghost"><a href="https://nello.sentry.io/" target="_blank" rel="noopener noreferrer">Abrir Sentry<ExternalLink className="ml-2 h-4 w-4"/><span className="sr-only">em nova aba</span></a></Button></div></CardContent></Card>;
}
export function IntelligenceContinuity(){
 const monitor=useAdminSource('intelligence-monitor',intelligenceContinuity);
 const query=useAdminSource('intelligence-health',intelligenceHealth);
 const labels={operational:'Sondagem respondeu',degraded:'Instabilidade parcial observada',unavailable:'Sondagem indisponível'};
 const assessment=monitor.data?.assessment;
 const stale=assessment&&(!assessment.latestCheckAt||Date.now()-Date.parse(assessment.latestCheckAt)>150000);
 const monitorLabel=stale?'Lacuna ou atraso nas verificações':({covered:'Cobertura completa nas janelas avaliadas',coverage_gap:'Lacuna ou atraso nas verificações',budget_burning:'Consumo do orçamento de erro observado',warming_up:'Amostra ainda insuficiente para seis horas'})[assessment?.state];
 return <div className="space-y-5">
  <Card className="rounded-2xl"><CardHeader><CardTitle className="text-lg">Cobertura do monitor independente</CardTitle><p className="text-sm text-muted-foreground">Verificações de produção a cada minuto, com janelas de cinco minutos a seis horas. A leitura não altera notificações do monitor.</p></CardHeader><CardContent className="space-y-3">
   <AdminSourceStatus query={monitor} queryOnly/>
   {monitor.data?.state==='available'?<><p className="font-medium">{monitorLabel}</p><p className="text-sm">Última verificação: {operationalDate(monitor.data.data_through)}</p><ul className="grid gap-2 sm:grid-cols-2">{Object.entries(assessment.windows).map(([minutes,w])=><li key={minutes} className="rounded-lg border p-3 text-sm">{minutes} min · {w.samples} amostras<p>{w.covered?'Janela coberta na avaliação':'Cobertura insuficiente'}</p></li>)}</ul><p className="text-xs text-muted-foreground">Referência operacional de disponibilidade: {assessment.availabilityPercent}%. Ausência de alerta não prova ausência de falhas.</p></>:monitor.data&&<p className="text-sm">{monitor.data.state==='not_configured'?'Leitura do monitor não configurada.':'Leitura não confirmada. Confira credencial, escopo e disponibilidade no provedor.'} Cobertura desconhecida.</p>}
  </CardContent></Card>
  <Card className="rounded-2xl"><CardHeader><CardTitle className="text-lg">Disponibilidade dos serviços</CardTitle><p className="text-sm text-muted-foreground">Sondagem pontual de Auth, banco e arquivos. Não representa o histórico ou a cobertura do monitor externo.</p></CardHeader><CardContent className="space-y-3"><AdminSourceStatus query={query} queryOnly/>{query.data&&<><p className="font-medium">{labels[query.data.status]}</p><ul className="space-y-2">{Object.entries(query.data.checks).map(([key,value])=><li key={key} className="flex flex-wrap justify-between gap-2 text-sm"><span>{({auth:'Autenticação',database:'Banco',storage:'Arquivos'})[key]}</span><span>{labels[value]}</span></li>)}</ul></>}<Button asChild variant="outline"><Link to="/status">Abrir status e comunicados</Link></Button><p className="text-xs text-muted-foreground">A ingestão analytics é conferida no workflow de observação. Consulte a evidência datada antes de concluir sobre cobertura ou disponibilidade contínua.</p></CardContent></Card>
  <section aria-labelledby="admin-runbooks" className="space-y-3"><h2 id="admin-runbooks" className="text-lg font-semibold">Procedimentos de investigação e recuperação</h2>{RUNBOOKS.map(book=><details key={book.id} className="rounded-xl border bg-card p-4"><summary className="cursor-pointer font-medium">{book.title}</summary><ol className="mt-3 list-decimal space-y-2 pl-5 text-sm">{book.steps.map(step=><li key={step}>{step}</li>)}</ol><Button asChild variant="outline" className="mt-4"><Link to={book.route}>Abrir área relacionada</Link></Button></details>)}</section>
 </div>;
}
