import React from 'react';
import { ArrowRight, ArrowUpRight, CalendarDays, Check, HeartHandshake, Leaf, MessageCircle, MonitorSmartphone, ShieldCheck, Users } from 'lucide-react';
import PublicSiteLayout, { PublicAction } from './PublicSiteLayout';
import { publicQuestions } from './publicSiteContent';
import { LandingHero, LandingPatientVisual, useLandingMotion } from './LandingExperience';
import { researchAuthors, researchAdvisor } from './researchContent';
import ProductScreenshot from './ProductScreenshot';

export default function LandingPage() {
  const { root, reduced, arrived } = useLandingMotion();
  return <PublicSiteLayout landing><main id="main-content" tabIndex={-1} className={`landing-experience${reduced ? ' landing-motion-paused' : ''}${arrived ? ' landing-arrived' : ''}`} ref={root}>
    <div className="landing-reading-progress" aria-hidden="true" /><LandingHero reduced={reduced} />
    <div className="landing-manifest"><div className="site-container"><span><Leaf aria-hidden="true" size={18} />Do consultório à rotina.</span><span>Organize.<i aria-hidden="true" />Planeje.<i aria-hidden="true" />Acompanhe.</span></div></div>
    <section className="landing-section site-container" aria-labelledby="site-features" data-reveal><div className="landing-section-heading"><span className="landing-kicker">01 / Seu consultório, conectado</span><h2 id="site-features">O consultório organizado.<br /><em>O paciente acompanhado.</em></h2><p>Reúna o histórico, prepare o plano e acompanhe a rotina. Cada recurso tem seu lugar no atendimento.</p></div><div className="site-feature-grid landing-bento">
      <article className="landing-bento-card landing-bento-plan"><span className="landing-card-label">Plano alimentar</span><h3>Seu conhecimento.<br />As possibilidades do dia a dia.</h3><p>Refeições, porções, medidas e alternativas. Organize um plano que faça sentido para cada pessoa.</p><a href="/recursos#recurso-planos" className="landing-card-link">Explore o planejamento<ArrowUpRight aria-hidden="true" size={20} /></a></article>
      <article className="landing-bento-card landing-bento-context"><span className="landing-card-label">Contexto clínico</span><Users aria-hidden="true" size={25} /><h3>Veja a pessoa.<br />Conecte a história.</h3><p>Pacientes, anamnese e avaliações reunidos para apoiar seu olhar clínico.</p><div className="landing-context-tags" aria-hidden="true"><span>História</span><span>Avaliações</span><span>Próximos passos</span></div><a href="/recursos#recurso-pacientes" className="landing-card-link">Conheça o prontuário<ArrowUpRight aria-hidden="true" size={20} /></a></article>
      <article className="landing-bento-card landing-bento-progress"><div className="landing-progress-copy"><span className="landing-card-label">Evolução</span><h3>O percurso também importa.</h3><p>Metas, registros e análise nutricional para orientar os próximos ajustes.</p><a href="/recursos#recurso-evolucao" className="landing-card-link">Explore o acompanhamento<ArrowUpRight aria-hidden="true" size={20} /></a></div><figure className="landing-progress-capture"><div className="public-phone-frame"><ProductScreenshot screen="progress" mobileOnly /></div><figcaption>Sua evolução, consulta após consulta.</figcaption></figure></article>
      <article className="landing-bento-card landing-bento-agenda"><span className="landing-card-label">Sua rotina profissional</span><div><CalendarDays aria-hidden="true" size={25} /><h3>Um lugar para o seu consultório.</h3></div><p>Agenda, consultas e financeiro conectados ao acompanhamento.</p><a href="/recursos" className="landing-card-link">Conheça todos os recursos<ArrowUpRight aria-hidden="true" size={20} /></a></article>
    </div></section>
    <section className="landing-journey" aria-labelledby="landing-journey-title"><div className="site-container landing-section" data-reveal><div className="landing-section-heading"><span className="landing-kicker">02 / Cuidado com continuidade</span><h2 id="landing-journey-title">Uma boa consulta<br /><em>é só o começo.</em></h2></div><div className="landing-journey-grid"><div className="landing-care-track" aria-hidden="true"><span /></div>{[[Users, '01', 'Conhecer', 'Comece pela pessoa.', 'Reúna a história, a anamnese e as avaliações para entender o contexto do acompanhamento.'], [Leaf, '02', 'Planejar', 'Dê forma ao seu cuidado.', 'Personalize refeições, porções e possibilidades. Revise o plano com o seu olhar profissional.'], [MessageCircle, '03', 'Acompanhar', 'Continue presente.', 'Acompanhe os registros e mantenha a comunicação entre uma consulta e outra.']].map(([Icon, number, label, title, text]) => <article key={number}><div className="landing-journey-node"><Icon aria-hidden="true" size={24} /><span>{number}</span></div><span className="landing-journey-label">{label}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="landing-section site-container landing-patient" aria-labelledby="site-patient" data-reveal><div><span className="landing-kicker">03 / A experiência do paciente</span><h2 id="site-patient">O cuidado precisa<br /><em>caber na vida.</em></h2><p>Seu paciente consulta o plano, registra as refeições e conversa com você pelo celular. As orientações ficam disponíveis entre as consultas.</p><ul className="landing-patient-list">{['Plano com porções e substituições', 'Diário para registrar a alimentação', 'Metas e evolução do acompanhamento'].map(text => <li key={text}><Check size={16} aria-hidden="true" />{text}</li>)}</ul><a href="/para-pacientes" className="landing-text-link">Conheça a área do paciente<ArrowRight aria-hidden="true" size={18} /></a></div><LandingPatientVisual /></section>
    <section className="landing-trust-section"><div className="site-container landing-section" data-reveal><div className="landing-section-heading"><span className="landing-kicker">04 / Confiança em cada etapa</span><h2>Conexão começa<br /><em>com transparência.</em></h2></div><div className="landing-trust-grid">{[[ShieldCheck, 'Privacidade e acesso', 'Conheça o uso dos dados e seus direitos de privacidade.', '/privacidade', 'Conhecer a privacidade'], [HeartHandshake, 'Ajuda quando precisar', 'Orientações de acesso e um canal de suporte para encontrar seu caminho.', '/ajuda', 'Encontrar ajuda'], [MonitorSmartphone, 'Disponibilidade à vista', 'Consulte o estado dos serviços e as orientações para proteger sua conta.', '/status', 'Consultar o status']].map(([Icon, title, text, href, label]) => <article key={title}><Icon aria-hidden="true" size={24} /><h3>{title}</h3><p>{text}</p><a href={href}>{label}<ArrowUpRight aria-hidden="true" size={17} /></a></article>)}</div></div></section>
    <section className="landing-section site-container landing-faq" aria-labelledby="site-faq-title" data-reveal><div><span className="landing-kicker">05 / Antes de começar</span><h2 id="site-faq-title">Vamos deixar<br /><em>mais claro.</em></h2><p>Entenda como começar, como convidar seus pacientes e onde encontrar ajuda.</p><a href="/ajuda" className="landing-text-link">Central de ajuda<ArrowRight aria-hidden="true" size={18} /></a></div><div className="site-faq-list">{publicQuestions.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>
    <section className="landing-research" aria-labelledby="landing-research-title"><div className="site-container landing-section research-project-grid" data-reveal><div><span className="landing-kicker">06 / Pesquisa e equipe · UNIMAR</span><h2 id="landing-research-title">Ouvir a experiência.<br /><em>Construir conhecimento.</em></h2><p>Alunos de Nutrição da Universidade de Marília (UNIMAR) estudam a experiência de uso de um software nutricional no projeto “Desenvolvimento e validação de um software nutricional”.</p><a href="/pesquisa" className="landing-text-link">Conheça o estudo e a equipe<ArrowRight aria-hidden="true" size={18} /></a></div><div><h3>Autoria do projeto de pesquisa</h3><ul className="landing-research-authors">{researchAuthors.map(name => <li key={name}>{name}</li>)}</ul><p className="landing-research-advisor"><strong>Orientação acadêmica</strong><br />{researchAdvisor}</p><p className="site-small">Projeto acadêmico de 2026. Sua apresentação não representa certificação clínica ou conclusão do TCC.</p></div></div></section>
    <section className="landing-final-cta" data-reveal aria-labelledby="landing-next-step"><div className="landing-final-orbit" aria-hidden="true" /><div className="site-container"><span className="landing-kicker">O próximo passo é seu.</span><h2 id="landing-next-step">Organize seu consultório.<br /><em>Aproxime o acompanhamento.</em></h2><p>Crie sua conta profissional para começar. Já recebeu um convite como paciente? Siga as orientações do seu nutricionista.</p><PublicAction /><a href="/login" className="landing-final-login">Já tem acesso? Entre no Nello<ArrowRight size={15} aria-hidden="true" /></a></div></section>
  </main></PublicSiteLayout>;
}
