import React from 'react';
import { ArrowRight, ArrowUpRight, Check, HeartHandshake, Leaf, MessageCircle, MonitorSmartphone, ShieldCheck, Users } from 'lucide-react';
import PublicSiteLayout, { PublicAction } from './PublicSiteLayout';
import { publicQuestions } from './publicSiteContent';
import { LandingHero, LandingPatientVisual, useLandingMotion } from './LandingExperience';
import { researchAuthors, researchAdvisor } from './researchContent';
import FeatureBenefitArt from './FeatureBenefitArt';

export default function LandingPage() {
  const { root, reduced, arrived } = useLandingMotion();
  return <PublicSiteLayout landing><main id="main-content" tabIndex={-1} className={`landing-experience${reduced ? ' landing-motion-paused' : ''}${arrived ? ' landing-arrived' : ''}`} ref={root}>
    <div className="landing-reading-progress" aria-hidden="true" /><LandingHero reduced={reduced} />
    <div className="landing-manifest"><div className="site-container"><span><Leaf aria-hidden="true" size={18} />Do consultório à rotina.</span><span>Organize.<i aria-hidden="true" />Planeje.<i aria-hidden="true" />Acompanhe.</span></div></div>
    <section className="landing-section site-container landing-features-section" aria-labelledby="site-features" data-reveal><div className="landing-section-heading"><span className="landing-kicker">01 / Seu consultório, conectado</span><h2 id="site-features">Mais espaço para cuidar.<br /><em>Menos informação espalhada.</em></h2><p>Da primeira consulta ao acompanhamento: encontre o que precisa para cada etapa do cuidado.</p></div><div className="site-feature-grid landing-feature-showcase landing-bento">
      {[
        { kind: 'plan', label: '01 / Planejamento', title: 'Planos que cabem na rotina.', text: 'Personalize refeições, porções e alternativas para cada paciente.', href: '/recursos#recurso-planos', action: 'Planejamento alimentar' },
        { kind: 'context', label: '02 / Contexto clínico', title: 'A história sempre por perto.', text: 'Reúna prontuário e avaliações para preparar o próximo encontro.', href: '/recursos#recurso-pacientes', action: 'Prontuário e avaliações' },
        { kind: 'progress', label: '03 / Acompanhamento', title: 'Presença entre as consultas.', text: 'Acompanhe medidas e registros para orientar os próximos ajustes.', href: '/recursos#recurso-evolucao', action: 'Evolução do paciente' },
        { kind: 'agenda', label: '04 / Organização', title: 'Seu dia com mais clareza.', text: 'Conecte agenda, consultas e financeiro à rotina do consultório.', href: '/recursos#recurso-consultorio', action: 'Gestão do consultório' },
      ].map(({ kind, label, title, text, href, action }) => <article key={kind} className={`landing-bento-card feature-panel feature-panel-${kind}`}>
        <div className="feature-panel-copy"><span className="feature-panel-label">{label}</span><h3>{title}</h3><p>{text}</p><a href={href} className="feature-panel-link">{action}<ArrowUpRight aria-hidden="true" size={18} /></a></div>
        <FeatureBenefitArt kind={kind} />
      </article>)}
    </div></section>
    <section className="landing-journey" aria-labelledby="landing-journey-title"><div className="site-container landing-section" data-reveal><div className="landing-section-heading"><span className="landing-kicker">02 / Cuidado com continuidade</span><h2 id="landing-journey-title">Uma boa consulta<br /><em>é só o começo.</em></h2></div><div className="landing-journey-grid"><div className="landing-care-track" aria-hidden="true"><span /></div>{[[Users, '01', 'Conhecer', 'Comece pela pessoa.', 'Reúna a história, a anamnese e as avaliações para entender o contexto do acompanhamento.'], [Leaf, '02', 'Planejar', 'Dê forma ao seu cuidado.', 'Personalize refeições, porções e possibilidades. Revise o plano com o seu olhar profissional.'], [MessageCircle, '03', 'Acompanhar', 'Continue presente.', 'Acompanhe os registros e mantenha a comunicação entre uma consulta e outra.']].map(([Icon, number, label, title, text]) => <article key={number}><div className="landing-journey-node"><Icon aria-hidden="true" size={24} /><span>{number}</span></div><span className="landing-journey-label">{label}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="landing-section site-container landing-patient" aria-labelledby="site-patient" data-reveal><div><span className="landing-kicker">03 / A experiência do paciente</span><h2 id="site-patient">O cuidado precisa<br /><em>caber na vida.</em></h2><p>Seu paciente consulta o plano, registra as refeições e conversa com você pelo celular. As orientações ficam disponíveis entre as consultas.</p><ul className="landing-patient-list">{['Plano com porções e substituições', 'Diário para registrar a alimentação', 'Metas e evolução do acompanhamento'].map(text => <li key={text}><Check size={16} aria-hidden="true" />{text}</li>)}</ul><a href="/para-pacientes" className="landing-text-link">Conheça a área do paciente<ArrowRight aria-hidden="true" size={18} /></a></div><LandingPatientVisual /></section>
    <section className="landing-trust-section"><div className="site-container landing-section" data-reveal><div className="landing-section-heading"><span className="landing-kicker">04 / Confiança em cada etapa</span><h2>Conexão começa<br /><em>com transparência.</em></h2></div><div className="landing-trust-grid">{[[ShieldCheck, 'Privacidade e acesso', 'Conheça o uso dos dados e seus direitos de privacidade.', '/privacidade', 'Conhecer a privacidade'], [HeartHandshake, 'Ajuda quando precisar', 'Orientações de acesso e um canal de suporte para encontrar seu caminho.', '/ajuda', 'Encontrar ajuda'], [MonitorSmartphone, 'Disponibilidade à vista', 'Consulte o estado dos serviços e as orientações para proteger sua conta.', '/status', 'Consultar o status']].map(([Icon, title, text, href, label]) => <article key={title}><Icon aria-hidden="true" size={24} /><h3>{title}</h3><p>{text}</p><a href={href}>{label}<ArrowUpRight aria-hidden="true" size={17} /></a></article>)}</div></div></section>
    <section className="landing-section site-container landing-faq" aria-labelledby="site-faq-title" data-reveal><div><span className="landing-kicker">05 / Antes de começar</span><h2 id="site-faq-title">Vamos deixar<br /><em>mais claro.</em></h2><p>Entenda como começar, como convidar seus pacientes e onde encontrar ajuda.</p><a href="/ajuda" className="landing-text-link">Central de ajuda<ArrowRight aria-hidden="true" size={18} /></a></div><div className="site-faq-list">{publicQuestions.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>
    <section className="landing-research" aria-labelledby="landing-research-title"><div className="site-container landing-section research-project-grid" data-reveal><div><span className="landing-kicker">06 / Pesquisa e equipe · UNIMAR</span><h2 id="landing-research-title">Ouvir a experiência.<br /><em>Construir conhecimento.</em></h2><p>Alunos de Nutrição da Universidade de Marília (UNIMAR) estudam a experiência de uso de um software nutricional no projeto “Desenvolvimento e validação de um software nutricional”.</p><a href="/pesquisa" className="landing-text-link">Conheça o estudo e a equipe<ArrowRight aria-hidden="true" size={18} /></a></div><div><h3>Autoria do projeto de pesquisa</h3><ul className="landing-research-authors">{researchAuthors.map(name => <li key={name}>{name}</li>)}</ul><p className="landing-research-advisor"><strong>Orientação acadêmica</strong><br />{researchAdvisor}</p><p className="site-small">Projeto acadêmico de 2026. Sua apresentação não representa certificação clínica ou conclusão do TCC.</p></div></div></section>
    <section className="landing-final-cta" data-reveal aria-labelledby="landing-next-step"><div className="landing-final-orbit" aria-hidden="true" /><div className="site-container"><span className="landing-kicker">O próximo passo é seu.</span><h2 id="landing-next-step">Organize seu consultório.<br /><em>Aproxime o acompanhamento.</em></h2><p>Crie sua conta profissional para começar. Já recebeu um convite como paciente? Siga as orientações do seu nutricionista.</p><PublicAction /><a href="/login" className="landing-final-login">Já tem acesso? Entre no Nello<ArrowRight size={15} aria-hidden="true" /></a></div></section>
  </main></PublicSiteLayout>;
}
