import React from 'react';
import { Check, ArrowRight } from 'lucide-react';
import PublicSiteLayout, { PublicAction, PublicNextStep } from './PublicSiteLayout';
import ProductIllustration from './ProductIllustration';
import { publicFeatures } from './publicSiteContent';

export default function ProductInformationPage({ pathname }) {
  const patient = pathname === '/para-pacientes';
  return <PublicSiteLayout activePath={pathname} landing><main id="main-content" tabIndex={-1} className="landing-experience public-product-experience">
    <section className="site-hero site-container"><div><span className="site-eyebrow">{patient ? 'Para quem recebe o cuidado' : 'Recursos para o consultório'}</span><h1>{patient ? <>Seu acompanhamento.<br /><em>Mais perto da sua rotina.</em></> : <>Seu olhar clínico.<br /><em>Um consultório conectado.</em></>}</h1><p>{patient ? 'Consulte o plano do seu nutricionista, registre a alimentação e acompanhe seus próximos passos em uma área feita para você.' : 'Pacientes, avaliações, planos, comunicação e gestão. Conheça os recursos que conectam as etapas do acompanhamento no Nello.'}</p><div className="site-hero-actions"><PublicAction href={patient ? '/login' : '/register'} compactLabel={patient ? 'Entrar' : 'Criar conta'}>{patient ? 'Acessar meu acompanhamento' : 'Criar minha conta'}</PublicAction><PublicAction href="/ajuda" secondary compactLabel={patient ? 'Ver convite' : 'Como começar'}>{patient ? 'Recebi um convite' : 'Como começar'}</PublicAction></div>{patient && <p className="site-small">Seu acompanhamento depende do vínculo com o nutricionista. Para começar, siga o convite recebido pelo email.</p>}</div><ProductIllustration patient={patient} /></section>
    <section className="site-section site-container"><div className="site-section-heading"><span className="site-eyebrow">{patient ? 'No seu dia a dia' : 'Conhecer. Planejar. Acompanhar.'}</span><h2>{patient ? 'Direção para cada etapa.' : 'Cada detalhe encontra seu lugar.'}</h2><p>{patient ? 'O profissional orienta o cuidado. O Nello ajuda a manter esse acompanhamento ao seu alcance.' : 'Recursos de apoio à sua prática, com informação clínica organizada e espaço para personalizar o acompanhamento.'}</p></div><div className="site-feature-grid">{(patient ? publicFeatures.filter((_,index)=>[2,3,5].includes(index)) : publicFeatures).map(({icon:Icon,title,detail})=><article className="site-feature" key={title}><span className="site-feature-icon"><Icon aria-hidden="true" size={22} /></span><h3>{title}</h3><p>{patient ? ({'Planos para a vida real.':'Veja o plano disponibilizado pelo seu nutricionista, com alimentos, quantidades e alternativas para as refeições.','Evolução em perspectiva.':'Consulte metas e evolução. Seus registros ajudam o profissional a entender sua rotina e ajustar o acompanhamento.','Uma conversa mais próxima.':'Registre a alimentação no diário e use as mensagens para conversar com o nutricionista durante o acompanhamento.'}[title]) : detail}</p></article>)}</div></section>
    <section className="site-dark-section"><div className="site-section site-container site-patient-section"><div className="site-section-heading"><span className="site-eyebrow">{patient ? 'Comece pelo convite' : 'Seu método, seu cuidado'}</span><h2>{patient ? 'Seu nutricionista conecta você ao Nello.' : 'Tecnologia como apoio. Você na direção.'}</h2><p>{patient ? 'Abra o email enviado pelo profissional, siga as orientações do convite e confirme o acesso. A ajuda reúne instruções para senha, confirmação de email e recuperação.' : 'Cálculos, modelos e documentos apoiam a organização do trabalho. A avaliação, a revisão do plano e as decisões clínicas continuam sendo do nutricionista.'}</p><a href={patient ? '/ajuda' : '/termos'} className="site-inline-link" style={{color:'#fff'}}>{patient ? 'Ver orientações de acesso' : 'Conhecer as condições de uso'}<ArrowRight aria-hidden="true" size={17} /></a></div><ul className="site-check-list">{(patient ? ['Use sua conta pessoal','Confira o plano com seu nutricionista','Procure o profissional para dúvidas clínicas'] : ['Personalize planos, refeições e medidas','Consulte análise nutricional e evolução','Organize consultas e comunicação']).map(text=><li key={text}><Check aria-hidden="true" style={{color:'#d5e1d5'}} />{text}</li>)}</ul></div></section>
    <section className="site-section site-container"><div className="site-section-heading"><span className="site-eyebrow">Próximos passos</span><h2>Conheça antes de começar.</h2><p>O Nello está em Beta. Encontre as orientações de acesso, conheça a privacidade e consulte o canal de suporte.</p><a href="/ajuda" className="site-inline-link">Encontrar ajuda<ArrowRight aria-hidden="true" size={17} /></a></div></section>
    {!patient && <PublicNextStep />}
  </main></PublicSiteLayout>;
}
