import React from 'react';
import { ArrowRight, BookOpen, GraduationCap, HeartHandshake } from 'lucide-react';
import PublicSiteLayout from './PublicSiteLayout';

import { researchAuthors as authors, researchAdvisor } from './researchContent';

export default function ResearchPage() {
  return <PublicSiteLayout activePath="/pesquisa" landing><main id="main-content" tabIndex={-1} className="landing-experience research-experience">
    <section className="site-subhero research-hero"><div className="site-container"><span className="landing-kicker">Pesquisa em Nutrição I · UNIMAR · 2026</span><h1>O cuidado inspira.<br /><em>A pesquisa aproxima.</em></h1><p>Conheça a pesquisa de usabilidade conduzida por alunos de Nutrição da UNIMAR e as pessoas responsáveis pelo projeto.</p><a href="#equipe-pesquisa" className="research-hero-link">Conheça a equipe<ArrowRight size={18} aria-hidden="true" /></a></div></section>
    <section className="site-container landing-section research-project"><span className="landing-kicker">01 / O projeto</span><div className="research-project-grid"><div><BookOpen aria-hidden="true" size={30} /><h2>Desenvolvimento e validação de um software nutricional</h2></div><div><p>Um projeto de pesquisa do curso de Nutrição da Universidade de Marília (UNIMAR), elaborado em 2026 na disciplina Pesquisa em Nutrição I.</p><p>O estudo considera a experiência de uso e a usabilidade de um software nutricional. Ouvir quem utiliza a tecnologia ajuda a identificar dificuldades e orientar melhorias no acompanhamento.</p><span className="research-status">Projeto de pesquisa acadêmica · 2026</span><p className="research-note">O título corresponde ao projeto acadêmico. Esta página apresenta sua proposta e autoria; não anuncia conclusão do TCC nem certificação clínica da plataforma.</p></div></div></section>
    <section className="site-container landing-section research-method" aria-labelledby="research-method-title"><span className="landing-kicker">Como a experiência foi avaliada</span><h2 id="research-method-title">Usabilidade percebida.<br /><em>Aprendizado para o produto.</em></h2><div className="research-method-grid"><article><h3>Quem participou</h3><p>A avaliação documentada reuniu estudantes de Nutrição e nutricionistas. Ela não inclui uma avaliação própria da experiência dos pacientes.</p></article><article><h3>O que foi observado</h3><p>As respostas à escala SUS (System Usability Scale) investigam a percepção de facilidade, integração das funções e confiança no uso do software.</p></article><article><h3>Como orienta melhorias</h3><p>O material ajuda a formular hipóteses sobre clareza, aprendizagem e previsibilidade. Novas versões precisam de novas avaliações de uso.</p></article></div><p className="research-note">A coleta documentada ocorreu em setembro de 2026 e antecede mudanças posteriores da interface. A avaliação de usabilidade não comprova resultados de saúde, exatidão de todos os cálculos ou certificação clínica. A consolidação dos documentos e resultados do TCC pertence à equipe de pesquisa.</p></section>
    <section id="equipe-pesquisa" className="research-team"><div className="site-container landing-section"><span className="landing-kicker">02 / As pessoas por trás do estudo</span><h2>Conhecimento que se constrói<br /><em>em conjunto.</em></h2><div className="research-credit-grid">{authors.map((name,index)=><article key={name}><span className="research-credit-number" aria-hidden="true">0{index+1}</span><GraduationCap aria-hidden="true" size={24} /><h3>{name}</h3><p>Autoria do projeto de pesquisa</p></article>)}</div><div className="research-advisor"><GraduationCap aria-hidden="true" size={27} /><div><span>Orientação acadêmica</span><h3>{researchAdvisor}</h3></div></div></div></section>
    <section className="site-container landing-section research-development"><HeartHandshake aria-hidden="true" size={30} /><div><span className="landing-kicker">03 / Tecnologia e pesquisa</span><h2>Perspectivas que<br /><em>se complementam.</em></h2><p>Vinicius Costa é responsável pelo desenvolvimento do Nello. A autoria do projeto de pesquisa e a orientação acadêmica pertencem à equipe creditada nesta página.</p><a href="/recursos" className="landing-text-link">Conheça os recursos do Nello<ArrowRight aria-hidden="true" size={18} /></a></div></section>
  </main></PublicSiteLayout>;
}
