import React from 'react';
import { ArrowRight, BookOpen, GraduationCap, HeartHandshake } from 'lucide-react';
import PublicSiteLayout from './PublicSiteLayout';

const authors = ['Brayan Vinicius Fazan de Sousa', 'Giulia Borges de Souza Bastos', 'Jonathan Shimite Santana', 'Lincoln Cardoso Single Souto', 'Marcello Hosho Tonon Filho'];

export default function ResearchPage() {
  return <PublicSiteLayout activePath="/pesquisa" landing><main id="main-content" tabIndex={-1} className="landing-experience research-experience">
    <section className="site-subhero research-hero"><div className="site-container"><span className="landing-kicker">Pesquisa em Nutrição I · UNIMAR · 2026</span><h1>O cuidado inspira.<br /><em>A pesquisa aproxima.</em></h1><p>Conheça o projeto acadêmico e as pessoas que estudam a experiência de uso de um software nutricional.</p><a href="#equipe-pesquisa" className="research-hero-link">Conheça a equipe<ArrowRight size={18} aria-hidden="true" /></a></div></section>
    <section className="site-container landing-section research-project"><span className="landing-kicker">01 / O projeto</span><div className="research-project-grid"><div><BookOpen aria-hidden="true" size={30} /><h2>Desenvolvimento e validação de um software nutricional</h2></div><div><p>Um projeto de pesquisa do curso de Nutrição da Universidade de Marília (UNIMAR), elaborado em 2026 na disciplina Pesquisa em Nutrição I.</p><p>O estudo considera a experiência de uso e a usabilidade de um software nutricional. Ouvir quem utiliza a tecnologia ajuda a identificar dificuldades e orientar melhorias no acompanhamento.</p><span className="research-status">Projeto de pesquisa acadêmica · 2026</span><p className="research-note">O título corresponde ao projeto acadêmico. Esta página apresenta sua proposta e autoria; não anuncia conclusão do TCC nem certificação clínica da plataforma.</p></div></div></section>
    <section id="equipe-pesquisa" className="research-team"><div className="site-container landing-section"><span className="landing-kicker">02 / As pessoas por trás do estudo</span><h2>Conhecimento que se constrói<br /><em>em conjunto.</em></h2><div className="research-credit-grid">{authors.map((name,index)=><article key={name}><span className="research-credit-number" aria-hidden="true">0{index+1}</span><GraduationCap aria-hidden="true" size={24} /><h3>{name}</h3><p>Autoria do projeto de pesquisa</p></article>)}</div><div className="research-advisor"><GraduationCap aria-hidden="true" size={27} /><div><span>Orientação acadêmica</span><h3>Profa. Dra. Cláudia Rucco Penteado Detregiachi</h3></div></div></div></section>
    <section className="site-container landing-section research-development"><HeartHandshake aria-hidden="true" size={30} /><div><span className="landing-kicker">03 / Tecnologia e pesquisa</span><h2>Perspectivas que<br /><em>se complementam.</em></h2><p>Vinicius Costa é responsável pelo desenvolvimento do Nello. A autoria do projeto de pesquisa e a orientação acadêmica pertencem à equipe creditada nesta página.</p><a href="/recursos" className="landing-text-link">Conheça os recursos do Nello<ArrowRight aria-hidden="true" size={18} /></a></div></section>
  </main></PublicSiteLayout>;
}
