-- Metadata only: never selects user profiles, patients, clinical rows or objects.
SELECT jsonb_build_object(
 'schemas', COALESCE((SELECT jsonb_agg(jsonb_build_object('name',nspname,'grants',nspacl::text) ORDER BY nspname) FROM pg_namespace WHERE nspname IN ('public','private')), '[]'::jsonb),
 'defaultPrivileges', COALESCE((SELECT jsonb_agg(jsonb_build_object('schema',n.nspname,'owner',r.rolname,'kind',d.defaclobjtype,'grants',d.defaclacl::text) ORDER BY n.nspname,r.rolname,d.defaclobjtype) FROM pg_default_acl d JOIN pg_namespace n ON n.oid=d.defaclnamespace JOIN pg_roles r ON r.oid=d.defaclrole WHERE n.nspname IN ('public','private')), '[]'::jsonb),
 'views', COALESCE((SELECT jsonb_agg(jsonb_build_object('schema',n.nspname,'name',c.relname,'options',c.reloptions,'definition',pg_get_viewdef(c.oid)) ORDER BY n.nspname,c.relname) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname IN ('public','private') AND c.relkind IN ('v','m')), '[]'::jsonb),
 'realtime', COALESCE((SELECT jsonb_agg(jsonb_build_object('schema',schemaname,'table',tablename,'columns',attnames,'rowFilter',rowfilter) ORDER BY schemaname,tablename) FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname IN ('public','private')), '[]'::jsonb),
 'relations', COALESCE((SELECT jsonb_agg(jsonb_build_object('schema',n.nspname,'name',c.relname,'kind',c.relkind,'rls',c.relrowsecurity,'forceRls',c.relforcerowsecurity,'grants',c.relacl::text) ORDER BY n.nspname,c.relname) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname IN ('public','private') AND c.relkind IN ('r','p','v','m','S')), '[]'::jsonb),
 'columns', COALESCE((SELECT jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'notNull',a.attnotnull,'identity',a.attidentity,'generated',a.attgenerated,'default',pg_get_expr(d.adbin,d.adrelid)) ORDER BY n.nspname,c.relname,a.attnum) FROM pg_attribute a JOIN pg_class c ON c.oid=a.attrelid JOIN pg_namespace n ON n.oid=c.relnamespace LEFT JOIN pg_attrdef d ON d.adrelid=c.oid AND d.adnum=a.attnum WHERE n.nspname IN ('public','private') AND c.relkind IN ('r','p','v','m') AND a.attnum>0 AND NOT a.attisdropped), '[]'::jsonb),
 'policies', COALESCE((SELECT jsonb_agg(to_jsonb(p) ORDER BY schemaname,tablename,policyname) FROM pg_policies p WHERE schemaname IN ('public','private','storage')), '[]'::jsonb),
 'functions', COALESCE((SELECT jsonb_agg(jsonb_build_object('schema',n.nspname,'name',p.proname,'args',pg_get_function_identity_arguments(p.oid),'returns',pg_get_function_result(p.oid),'definer',p.prosecdef,'config',p.proconfig,'grants',p.proacl::text,'definition',md5(replace(pg_get_functiondef(p.oid), E'\r\n', E'\n'))) ORDER BY n.nspname,p.proname,pg_get_function_identity_arguments(p.oid)) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname IN ('public','private') AND p.prokind IN ('f','p') AND NOT EXISTS (SELECT 1 FROM pg_depend dep WHERE dep.objid=p.oid AND dep.deptype='e')), '[]'::jsonb),
 'constraints', COALESCE((SELECT jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'name',con.conname,'definition',pg_get_constraintdef(con.oid)) ORDER BY n.nspname,c.relname,con.conname) FROM pg_constraint con JOIN pg_class c ON c.oid=con.conrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname IN ('public','private')), '[]'::jsonb),
 'triggers', COALESCE((SELECT jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'name',t.tgname,'definition',pg_get_triggerdef(t.oid),'enabled',t.tgenabled) ORDER BY n.nspname,c.relname,t.tgname) FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE NOT t.tgisinternal AND (n.nspname IN ('public','private') OR (n.nspname='auth' AND c.relname='users'))), '[]'::jsonb),
 'indexes', COALESCE((SELECT jsonb_agg(to_jsonb(i) ORDER BY schemaname,tablename,indexname) FROM pg_indexes i WHERE schemaname IN ('public','private')), '[]'::jsonb),
 'enums', COALESCE((SELECT jsonb_agg(jsonb_build_object('schema',n.nspname,'type',t.typname,'label',e.enumlabel,'order',e.enumsortorder) ORDER BY n.nspname,t.typname,e.enumsortorder) FROM pg_enum e JOIN pg_type t ON t.oid=e.enumtypid JOIN pg_namespace n ON n.oid=t.typnamespace WHERE n.nspname IN ('public','private')), '[]'::jsonb),
 'buckets', COALESCE((SELECT jsonb_agg(jsonb_build_object('id',id,'name',name,'public',public,'file_size_limit',file_size_limit,'allowed_mime_types',allowed_mime_types) ORDER BY id) FROM storage.buckets), '[]'::jsonb)
) AS catalog;
