import React,{useRef,useState} from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { useAdminSource,accessDenied } from '@/portals/admin/hooks/useAdminSource';
import { supportQueue,supportCreate,supportGateway } from '@/features/admin/services/supportService';
import { CASE_STATES,CASE_CATEGORIES,supportDate,supportError } from '@/portals/admin/model/support';
import SupportCasePanel from '@/portals/admin/components/SupportCasePanel';
import AdminSourceStatus from '@/portals/admin/components/AdminSourceStatus';
import { Card,CardHeader,CardTitle,CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';

function SupportWorkspace(){
 const [filter,setFilter]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState(null),[creating,setCreating]=useState(false),[subject,setSubject]=useState(''),[email,setEmail]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sync,setSync]=useState(null);
 const intention=useRef(null);const queue=useAdminSource(['support',filter,page],()=>supportQueue(filter,page));const provider=useAdminSource(['support-provider'],()=>supportGateway('status'));const data=queue.data;
 async function reconcile(){setBusy(true);setError('');try{const result=await supportGateway('sync',{cursor:sync?.cursor||null});if(result.error)throw result.error;setSync(result.data);await queue.refetch();}catch(failure){setError(supportError(failure));}finally{setBusy(false);}}
 async function create(e){e.preventDefault();setBusy(true);setError('');const fingerprint=JSON.stringify([subject,email]);if(intention.current?.fingerprint!==fingerprint)intention.current={fingerprint,nonce:crypto.randomUUID()};try{const result=await supportCreate({subject,email,nonce:intention.current.nonce});if(result.error)throw result.error;if(result.data?.success!==true)throw Error('unconfirmed_creation');setSelected(result.data.id);setCreating(false);setSubject('');setEmail('');intention.current=null;await queue.refetch();}catch(failure){setError(supportError(failure));}finally{setBusy(false);}}
 return <div className="space-y-6 min-w-0 ph-no-capture" data-ph-no-capture><div><h1 className="text-3xl font-bold">Atendimento e feedback</h1><p className="mt-2 text-sm text-muted-foreground">Mensagens privadas, respostas revisadas e acompanhamento de melhorias.</p></div>
  <Card><CardHeader><CardTitle className="tracking-normal [word-spacing:.08em]">Caixa de suporte</CardTitle></CardHeader><CardContent className="space-y-4"><AdminSourceStatus query={queue} queryOnly/>
   <div className="rounded-md border p-3 text-sm"><p>{provider.data?.configured?'Gateway Resend configurado.':'Consulta/configuração do Resend ainda não confirmada.'} {provider.data?.webhook_configured?'Assinatura de webhook configurada.':'Recebimento automático ainda não confirmado.'}</p><p className="mt-1 text-xs text-muted-foreground">Aceitação, entrega e leitura humana são estados distintos. Horários de atendimento usam horas corridas.</p></div>
   {error&&<p role="alert" className="text-sm">{error}</p>}
   <div className="flex flex-wrap gap-3"><select aria-label="Filtrar atendimento" className="h-11 max-w-full rounded-md border bg-background px-3 text-sm" value={filter} onChange={e=>{setFilter(e.target.value);setPage(1);}}><option value="">Todos os estados</option>{Object.entries(CASE_STATES).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>{data?.can_write&&<><Button variant="outline" disabled={busy||!provider.data?.configured} onClick={()=>void reconcile()}>{sync?.has_more?'Importar próxima página':'Conferir recebimento no Resend'}</Button><Button onClick={()=>setCreating(n=>!n)} disabled={busy}>Novo caso</Button></>}</div>
   {sync&&<p role="status" className="text-sm">{sync.imported} mensagens novas importadas nesta página · {supportDate(sync.checked_at)}. {sync.has_more?'Há mensagens anteriores; continue a reconciliação.':'Fim desta consulta.'}</p>}
   {data&&<div className="grid gap-3 sm:grid-cols-3"><p className="rounded-lg bg-muted p-3 text-sm"><strong className="block text-xl">{data.metrics.open}</strong>Casos abertos</p><p className="rounded-lg bg-muted p-3 text-sm"><strong className="block text-xl">{data.metrics.unknown_sends}</strong>Envios aguardando confirmação</p><p className="rounded-lg bg-muted p-3 text-sm"><strong className="block text-xl">{data.metrics.first_reply_p50_hours==null?'Sem amostra':`${Number(data.metrics.first_reply_p50_hours).toLocaleString('pt-BR',{maximumFractionDigits:1})} h`}</strong>Mediana até primeira resposta aceita · {data.metrics.first_reply_sample} casos em 30 dias</p></div>}
   {creating&&data?.can_write&&<form onSubmit={create} className="space-y-3 rounded-lg border p-4"><div className="space-y-2"><Label htmlFor="support-new-subject">Assunto</Label><Input id="support-new-subject" value={subject} onChange={e=>setSubject(e.target.value)} maxLength={200} required disabled={busy}/></div><div className="space-y-2"><Label htmlFor="support-new-email">E-mail de contato</Label><Input id="support-new-email" type="email" value={email} onChange={e=>setEmail(e.target.value)} maxLength={254} required disabled={busy}/></div><Button disabled={busy}>Criar atendimento</Button></form>}
   <div className="space-y-2">{data?.items.map(item=><button key={item.id} type="button" className="flex w-full flex-wrap items-center justify-between gap-3 rounded-lg border bg-card p-4 text-left hover:bg-accent focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" onClick={()=>setSelected(item.id)}><span className="min-w-0 flex-1"><strong className="block break-words">{item.subject}</strong><span className="block break-all text-sm text-muted-foreground">{item.contact_email}</span><span className="text-xs text-muted-foreground">{supportDate(item.updated_at)}</span></span><span className="flex flex-wrap gap-2"><Badge>{CASE_STATES[item.status]}</Badge><Badge variant="secondary">{CASE_CATEGORIES[item.category]}</Badge></span></button>)}{data?.items.length===0&&!queue.isError&&<p className="py-6 text-center text-sm text-muted-foreground">Nenhum atendimento neste filtro. Confira o recebimento ou registre um caso.</p>}</div>
   <div className="flex flex-wrap items-center justify-between gap-2 text-sm"><span>Página {page} · {data?.total??'—'} casos</span><div className="flex gap-2"><Button variant="outline" disabled={page<=1||queue.isFetching} onClick={()=>setPage(n=>n-1)}>Anterior</Button><Button variant="outline" disabled={!data||page*20>=data.total||queue.isFetching} onClick={()=>setPage(n=>n+1)}>Próxima</Button></div></div>
  </CardContent></Card>
  {selected&&!accessDenied(queue.error)&&<SupportCasePanel key={selected} id={selected} canWriteCeiling={data?.can_write} onQueueRefresh={()=>queue.refetch()} onClose={()=>setSelected(null)}/>}
 </div>;
}
export default function AdminSupportPage(){const {user}=useAuth();return <SupportWorkspace key={user?.id}/>;}
